export const classes = [
    {className: "bg-fixed", rules: "background-attachment: fixed;"},
    {className: "bg-local", rules: "background-attachment: local;"},
    {className: "bg-scroll", rules: "background-attachment: scroll;"},
    {className: "bg-clip-border", rules: "background-clip: border-box;"},
    {className: "bg-clip-padding", rules: "background-clip: padding-box;"},
    {className: "bg-clip-content", rules: "background-clip: content-box;"},
    {className: "bg-clip-text", rules: "background-clip: text;"},
    {className: "bg-transparent", rules: "background-color: transparent;"},
    {className: "bg-current", rules: "background-color: currentColor;"},
    {className: "bg-black", rules: "--tw-bg-opacity: 1;background-color: rgba(0, 0, 0, var(--tw-bg-opacity));"},
    {className: "bg-white", rules: "--tw-bg-opacity: 1;background-color: rgba(255, 255, 255, var(--tw-bg-opacity));"},
    {className: "bg-gray-50", rules: "--tw-bg-opacity: 1;background-color: rgba(249, 250, 251, var(--tw-bg-opacity));"},
    {className: "bg-gray-100", rules: "--tw-bg-opacity: 1;background-color: rgba(243, 244, 246, var(--tw-bg-opacity));"},
    {className: "bg-gray-200", rules: "--tw-bg-opacity: 1;background-color: rgba(229, 231, 235, var(--tw-bg-opacity));"},
    {className: "bg-gray-300", rules: "--tw-bg-opacity: 1;background-color: rgba(209, 213, 219, var(--tw-bg-opacity));"},
    {className: "bg-gray-400", rules: "--tw-bg-opacity: 1;background-color: rgba(156, 163, 175, var(--tw-bg-opacity));"},
    {className: "bg-gray-500", rules: "--tw-bg-opacity: 1;background-color: rgba(107, 114, 128, var(--tw-bg-opacity));"},
    {className: "bg-gray-600", rules: "--tw-bg-opacity: 1;background-color: rgba(75, 85, 99, var(--tw-bg-opacity));"},
    {className: "bg-gray-700", rules: "--tw-bg-opacity: 1;background-color: rgba(55, 65, 81, var(--tw-bg-opacity));"},
    {className: "bg-gray-800", rules: "--tw-bg-opacity: 1;background-color: rgba(31, 41, 55, var(--tw-bg-opacity));"},
    {className: "bg-gray-900", rules: "--tw-bg-opacity: 1;background-color: rgba(17, 24, 39, var(--tw-bg-opacity));"},
    {className: "bg-red-50", rules: "--tw-bg-opacity: 1;background-color: rgba(254, 242, 242, var(--tw-bg-opacity));"},
    {className: "bg-red-100", rules: "--tw-bg-opacity: 1;background-color: rgba(254, 226, 226, var(--tw-bg-opacity));"},
    {className: "bg-red-200", rules: "--tw-bg-opacity: 1;background-color: rgba(254, 202, 202, var(--tw-bg-opacity));"},
    {className: "bg-red-300", rules: "--tw-bg-opacity: 1;background-color: rgba(252, 165, 165, var(--tw-bg-opacity));"},
    {className: "bg-red-400", rules: "--tw-bg-opacity: 1;background-color: rgba(248, 113, 113, var(--tw-bg-opacity));"},
    {className: "bg-red-500", rules: "--tw-bg-opacity: 1;background-color: rgba(239, 68, 68, var(--tw-bg-opacity));"},
    {className: "bg-red-600", rules: "--tw-bg-opacity: 1;background-color: rgba(220, 38, 38, var(--tw-bg-opacity));"},
    {className: "bg-red-700", rules: "--tw-bg-opacity: 1;background-color: rgba(185, 28, 28, var(--tw-bg-opacity));"},
    {className: "bg-red-800", rules: "--tw-bg-opacity: 1;background-color: rgba(153, 27, 27, var(--tw-bg-opacity));"},
    {className: "bg-red-900", rules: "--tw-bg-opacity: 1;background-color: rgba(127, 29, 29, var(--tw-bg-opacity));"},
    {className: "bg-yellow-50", rules: "--tw-bg-opacity: 1;background-color: rgba(255, 251, 235, var(--tw-bg-opacity));"},
    {className: "bg-yellow-100", rules: "--tw-bg-opacity: 1;background-color: rgba(254, 243, 199, var(--tw-bg-opacity));"},
    {className: "bg-yellow-200", rules: "--tw-bg-opacity: 1;background-color: rgba(253, 230, 138, var(--tw-bg-opacity));"},
    {className: "bg-yellow-300", rules: "--tw-bg-opacity: 1;background-color: rgba(252, 211, 77, var(--tw-bg-opacity));"},
    {className: "bg-yellow-400", rules: "--tw-bg-opacity: 1;background-color: rgba(251, 191, 36, var(--tw-bg-opacity));"},
    {className: "bg-yellow-500", rules: "--tw-bg-opacity: 1;background-color: rgba(245, 158, 11, var(--tw-bg-opacity));"},
    {className: "bg-yellow-600", rules: "--tw-bg-opacity: 1;background-color: rgba(217, 119, 6, var(--tw-bg-opacity));"},
    {className: "bg-yellow-700", rules: "--tw-bg-opacity: 1;background-color: rgba(180, 83, 9, var(--tw-bg-opacity));"},
    {className: "bg-yellow-800", rules: "--tw-bg-opacity: 1;background-color: rgba(146, 64, 14, var(--tw-bg-opacity));"},
    {className: "bg-yellow-900", rules: "--tw-bg-opacity: 1;background-color: rgba(120, 53, 15, var(--tw-bg-opacity));"},
    {className: "bg-green-50", rules: "--tw-bg-opacity: 1;background-color: rgba(236, 253, 245, var(--tw-bg-opacity));"},
    {className: "bg-green-100", rules: "--tw-bg-opacity: 1;background-color: rgba(209, 250, 229, var(--tw-bg-opacity));"},
    {className: "bg-green-200", rules: "--tw-bg-opacity: 1;background-color: rgba(167, 243, 208, var(--tw-bg-opacity));"},
    {className: "bg-green-300", rules: "--tw-bg-opacity: 1;background-color: rgba(110, 231, 183, var(--tw-bg-opacity));"},
    {className: "bg-green-400", rules: "--tw-bg-opacity: 1;background-color: rgba(52, 211, 153, var(--tw-bg-opacity));"},
    {className: "bg-green-500", rules: "--tw-bg-opacity: 1;background-color: rgba(16, 185, 129, var(--tw-bg-opacity));"},
    {className: "bg-green-600", rules: "--tw-bg-opacity: 1;background-color: rgba(5, 150, 105, var(--tw-bg-opacity));"},
    {className: "bg-green-700", rules: "--tw-bg-opacity: 1;background-color: rgba(4, 120, 87, var(--tw-bg-opacity));"},
    {className: "bg-green-800", rules: "--tw-bg-opacity: 1;background-color: rgba(6, 95, 70, var(--tw-bg-opacity));"},
    {className: "bg-green-900", rules: "--tw-bg-opacity: 1;background-color: rgba(6, 78, 59, var(--tw-bg-opacity));"},
    {className: "bg-blue-50", rules: "--tw-bg-opacity: 1;background-color: rgba(239, 246, 255, var(--tw-bg-opacity));"},
    {className: "bg-blue-100", rules: "--tw-bg-opacity: 1;background-color: rgba(219, 234, 254, var(--tw-bg-opacity));"},
    {className: "bg-blue-200", rules: "--tw-bg-opacity: 1;background-color: rgba(191, 219, 254, var(--tw-bg-opacity));"},
    {className: "bg-blue-300", rules: "--tw-bg-opacity: 1;background-color: rgba(147, 197, 253, var(--tw-bg-opacity));"},
    {className: "bg-blue-400", rules: "--tw-bg-opacity: 1;background-color: rgba(96, 165, 250, var(--tw-bg-opacity));"},
    {className: "bg-blue-500", rules: "--tw-bg-opacity: 1;background-color: rgba(59, 130, 246, var(--tw-bg-opacity));"},
    {className: "bg-blue-600", rules: "--tw-bg-opacity: 1;background-color: rgba(37, 99, 235, var(--tw-bg-opacity));"},
    {className: "bg-blue-700", rules: "--tw-bg-opacity: 1;background-color: rgba(29, 78, 216, var(--tw-bg-opacity));"},
    {className: "bg-blue-800", rules: "--tw-bg-opacity: 1;background-color: rgba(30, 64, 175, var(--tw-bg-opacity));"},
    {className: "bg-blue-900", rules: "--tw-bg-opacity: 1;background-color: rgba(30, 58, 138, var(--tw-bg-opacity));"},
    {className: "bg-indigo-50", rules: "--tw-bg-opacity: 1;background-color: rgba(238, 242, 255, var(--tw-bg-opacity));"},
    {className: "bg-indigo-100", rules: "--tw-bg-opacity: 1;background-color: rgba(224, 231, 255, var(--tw-bg-opacity));"},
    {className: "bg-indigo-200", rules: "--tw-bg-opacity: 1;background-color: rgba(199, 210, 254, var(--tw-bg-opacity));"},
    {className: "bg-indigo-300", rules: "--tw-bg-opacity: 1;background-color: rgba(165, 180, 252, var(--tw-bg-opacity));"},
    {className: "bg-indigo-400", rules: "--tw-bg-opacity: 1;background-color: rgba(129, 140, 248, var(--tw-bg-opacity));"},
    {className: "bg-indigo-500", rules: "--tw-bg-opacity: 1;background-color: rgba(99, 102, 241, var(--tw-bg-opacity));"},
    {className: "bg-indigo-600", rules: "--tw-bg-opacity: 1;background-color: rgba(79, 70, 229, var(--tw-bg-opacity));"},
    {className: "bg-indigo-700", rules: "--tw-bg-opacity: 1;background-color: rgba(67, 56, 202, var(--tw-bg-opacity));"},
    {className: "bg-indigo-800", rules: "--tw-bg-opacity: 1;background-color: rgba(55, 48, 163, var(--tw-bg-opacity));"},
    {className: "bg-indigo-900", rules: "--tw-bg-opacity: 1;background-color: rgba(49, 46, 129, var(--tw-bg-opacity));"},
    {className: "bg-purple-50", rules: "--tw-bg-opacity: 1;background-color: rgba(245, 243, 255, var(--tw-bg-opacity));"},
    {className: "bg-purple-100", rules: "--tw-bg-opacity: 1;background-color: rgba(237, 233, 254, var(--tw-bg-opacity));"},
    {className: "bg-purple-200", rules: "--tw-bg-opacity: 1;background-color: rgba(221, 214, 254, var(--tw-bg-opacity));"},
    {className: "bg-purple-300", rules: "--tw-bg-opacity: 1;background-color: rgba(196, 181, 253, var(--tw-bg-opacity));"},
    {className: "bg-purple-400", rules: "--tw-bg-opacity: 1;background-color: rgba(167, 139, 250, var(--tw-bg-opacity));"},
    {className: "bg-purple-500", rules: "--tw-bg-opacity: 1;background-color: rgba(139, 92, 246, var(--tw-bg-opacity));"},
    {className: "bg-purple-600", rules: "--tw-bg-opacity: 1;background-color: rgba(124, 58, 237, var(--tw-bg-opacity));"},
    {className: "bg-purple-700", rules: "--tw-bg-opacity: 1;background-color: rgba(109, 40, 217, var(--tw-bg-opacity));"},
    {className: "bg-purple-800", rules: "--tw-bg-opacity: 1;background-color: rgba(91, 33, 182, var(--tw-bg-opacity));"},
    {className: "bg-purple-900", rules: "--tw-bg-opacity: 1;background-color: rgba(76, 29, 149, var(--tw-bg-opacity));"},
    {className: "bg-pink-50", rules: "--tw-bg-opacity: 1;background-color: rgba(253, 242, 248, var(--tw-bg-opacity));"},
    {className: "bg-pink-100", rules: "--tw-bg-opacity: 1;background-color: rgba(252, 231, 243, var(--tw-bg-opacity));"},
    {className: "bg-pink-200", rules: "--tw-bg-opacity: 1;background-color: rgba(251, 207, 232, var(--tw-bg-opacity));"},
    {className: "bg-pink-300", rules: "--tw-bg-opacity: 1;background-color: rgba(249, 168, 212, var(--tw-bg-opacity));"},
    {className: "bg-pink-400", rules: "--tw-bg-opacity: 1;background-color: rgba(244, 114, 182, var(--tw-bg-opacity));"},
    {className: "bg-pink-500", rules: "--tw-bg-opacity: 1;background-color: rgba(236, 72, 153, var(--tw-bg-opacity));"},
    {className: "bg-pink-600", rules: "--tw-bg-opacity: 1;background-color: rgba(219, 39, 119, var(--tw-bg-opacity));"},
    {className: "bg-pink-700", rules: "--tw-bg-opacity: 1;background-color: rgba(190, 24, 93, var(--tw-bg-opacity));"},
    {className: "bg-pink-800", rules: "--tw-bg-opacity: 1;background-color: rgba(157, 23, 77, var(--tw-bg-opacity));"},
    {className: "bg-pink-900", rules: "--tw-bg-opacity: 1;background-color: rgba(131, 24, 67, var(--tw-bg-opacity));"},
    {className: "bg-opacity-0", rules: "--tw-bg-opacity: 0;"},
    {className: "bg-opacity-5", rules: "--tw-bg-opacity: 0.05;"},
    {className: "bg-opacity-10", rules: "--tw-bg-opacity: 0.1;"},
    {className: "bg-opacity-20", rules: "--tw-bg-opacity: 0.2;"},
    {className: "bg-opacity-25", rules: "--tw-bg-opacity: 0.25;"},
    {className: "bg-opacity-30", rules: "--tw-bg-opacity: 0.3;"},
    {className: "bg-opacity-40", rules: "--tw-bg-opacity: 0.4;"},
    {className: "bg-opacity-50", rules: "--tw-bg-opacity: 0.5;"},
    {className: "bg-opacity-60", rules: "--tw-bg-opacity: 0.6;"},
    {className: "bg-opacity-70", rules: "--tw-bg-opacity: 0.7;"},
    {className: "bg-opacity-75", rules: "--tw-bg-opacity: 0.75;"},
    {className: "bg-opacity-80", rules: "--tw-bg-opacity: 0.8;"},
    {className: "bg-opacity-90", rules: "--tw-bg-opacity: 0.9;"},
    {className: "bg-opacity-95", rules: "--tw-bg-opacity: 0.95;"},
    {className: "bg-opacity-100", rules: "--tw-bg-opacity: 1;"},
    {className: "bg-bottom", rules: "background-position: bottom;"},
    {className: "bg-center", rules: "background-position: center;"},
    {className: "bg-left", rules: "background-position: left;"},
    {className: "bg-left-bottom", rules: "background-position: left bottom;"},
    {className: "bg-left-top", rules: "background-position: left top;"},
    {className: "bg-right", rules: "background-position: right;"},
    {className: "bg-right-bottom", rules: "background-position: right bottom;"},
    {className: "bg-right-top", rules: "background-position: right top;"},
    {className: "bg-top", rules: "background-position: top;"},
    {className: "bg-repeat", rules: "background-repeat: repeat;"},
    {className: "bg-no-repeat", rules: "background-repeat: no-repeat;"},
    {className: "bg-repeat-x", rules: "background-repeat: repeat-x;"},
    {className: "bg-repeat-y", rules: "background-repeat: repeat-y;"},
    {className: "bg-repeat-round", rules: "background-repeat: round;"},
    {className: "bg-repeat-space", rules: "background-repeat: space;"},
    {className: "bg-auto", rules: "background-size: auto;"},
    {className: "bg-cover", rules: "background-size: cover;"},
    {className: "bg-contain", rules: "background-size: contain;"},
    {className: "bg-none", rules: "background-image: none;"},
    {className: "bg-gradient-to-t", rules: "background-image: linear-gradient(to top, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-tr", rules: "background-image: linear-gradient(to top right, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-r", rules: "background-image: linear-gradient(to right, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-br", rules: "background-image: linear-gradient(to bottom right, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-b", rules: "background-image: linear-gradient(to bottom, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-bl", rules: "background-image: linear-gradient(to bottom left, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-l", rules: "background-image: linear-gradient(to left, var(--tw-gradient-stops));"},
    {className: "bg-gradient-to-tl", rules: "background-image: linear-gradient(to top left, var(--tw-gradient-stops));"},
    {className: "from-transparent", rules: "--tw-gradient-from: transparent;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(0, 0, 0, 0));"},
    {className: "from-current", rules: "--tw-gradient-from: currentColor;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(255, 255, 255, 0));"},
    {className: "from-black", rules: "--tw-gradient-from: #000;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(0, 0, 0, 0));"},
    {className: "from-white", rules: "--tw-gradient-from: #fff;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(255, 255, 255, 0));"},
    {className: "from-gray-50", rules: "--tw-gradient-from: #f9fafb;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(249, 250, 251, 0));"},
    {className: "from-gray-100", rules: "--tw-gradient-from: #f3f4f6;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(243, 244, 246, 0));"},
    {className: "from-gray-200", rules: "--tw-gradient-from: #e5e7eb;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(229, 231, 235, 0));"},
    {className: "from-gray-300", rules: "--tw-gradient-from: #d1d5db;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(209, 213, 219, 0));"},
    {className: "from-gray-400", rules: "--tw-gradient-from: #9ca3af;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(156, 163, 175, 0));"},
    {className: "from-gray-500", rules: "--tw-gradient-from: #6b7280;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(107, 114, 128, 0));"},
    {className: "from-gray-600", rules: "--tw-gradient-from: #4b5563;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(75, 85, 99, 0));"},
    {className: "from-gray-700", rules: "--tw-gradient-from: #374151;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(55, 65, 81, 0));"},
    {className: "from-gray-800", rules: "--tw-gradient-from: #1f2937;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(31, 41, 55, 0));"},
    {className: "from-gray-900", rules: "--tw-gradient-from: #111827;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(17, 24, 39, 0));"},
    {className: "from-red-50", rules: "--tw-gradient-from: #fef2f2;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(254, 242, 242, 0));"},
    {className: "from-red-100", rules: "--tw-gradient-from: #fee2e2;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(254, 226, 226, 0));"},
    {className: "from-red-200", rules: "--tw-gradient-from: #fecaca;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(254, 202, 202, 0));"},
    {className: "from-red-300", rules: "--tw-gradient-from: #fca5a5;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(252, 165, 165, 0));"},
    {className: "from-red-400", rules: "--tw-gradient-from: #f87171;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(248, 113, 113, 0));"},
    {className: "from-red-500", rules: "--tw-gradient-from: #ef4444;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(239, 68, 68, 0));"},
    {className: "from-red-600", rules: "--tw-gradient-from: #dc2626;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(220, 38, 38, 0));"},
    {className: "from-red-700", rules: "--tw-gradient-from: #b91c1c;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(185, 28, 28, 0));"},
    {className: "from-red-800", rules: "--tw-gradient-from: #991b1b;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(153, 27, 27, 0));"},
    {className: "from-red-900", rules: "--tw-gradient-from: #7f1d1d;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(127, 29, 29, 0));"},
    {className: "from-yellow-50", rules: "--tw-gradient-from: #fffbeb;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(255, 251, 235, 0));"},
    {className: "from-yellow-100", rules: "--tw-gradient-from: #fef3c7;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(254, 243, 199, 0));"},
    {className: "from-yellow-200", rules: "--tw-gradient-from: #fde68a;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(253, 230, 138, 0));"},
    {className: "from-yellow-300", rules: "--tw-gradient-from: #fcd34d;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(252, 211, 77, 0));"},
    {className: "from-yellow-400", rules: "--tw-gradient-from: #fbbf24;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(251, 191, 36, 0));"},
    {className: "from-yellow-500", rules: "--tw-gradient-from: #f59e0b;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(245, 158, 11, 0));"},
    {className: "from-yellow-600", rules: "--tw-gradient-from: #d97706;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(217, 119, 6, 0));"},
    {className: "from-yellow-700", rules: "--tw-gradient-from: #b45309;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(180, 83, 9, 0));"},
    {className: "from-yellow-800", rules: "--tw-gradient-from: #92400e;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(146, 64, 14, 0));"},
    {className: "from-yellow-900", rules: "--tw-gradient-from: #78350f;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(120, 53, 15, 0));"},
    {className: "from-green-50", rules: "--tw-gradient-from: #ecfdf5;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(236, 253, 245, 0));"},
    {className: "from-green-100", rules: "--tw-gradient-from: #d1fae5;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(209, 250, 229, 0));"},
    {className: "from-green-200", rules: "--tw-gradient-from: #a7f3d0;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(167, 243, 208, 0));"},
    {className: "from-green-300", rules: "--tw-gradient-from: #6ee7b7;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(110, 231, 183, 0));"},
    {className: "from-green-400", rules: "--tw-gradient-from: #34d399;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(52, 211, 153, 0));"},
    {className: "from-green-500", rules: "--tw-gradient-from: #10b981;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(16, 185, 129, 0));"},
    {className: "from-green-600", rules: "--tw-gradient-from: #059669;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(5, 150, 105, 0));"},
    {className: "from-green-700", rules: "--tw-gradient-from: #047857;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(4, 120, 87, 0));"},
    {className: "from-green-800", rules: "--tw-gradient-from: #065f46;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(6, 95, 70, 0));"},
    {className: "from-green-900", rules: "--tw-gradient-from: #064e3b;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(6, 78, 59, 0));"},
    {className: "from-blue-50", rules: "--tw-gradient-from: #eff6ff;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(239, 246, 255, 0));"},
    {className: "from-blue-100", rules: "--tw-gradient-from: #dbeafe;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(219, 234, 254, 0));"},
    {className: "from-blue-200", rules: "--tw-gradient-from: #bfdbfe;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(191, 219, 254, 0));"},
    {className: "from-blue-300", rules: "--tw-gradient-from: #93c5fd;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(147, 197, 253, 0));"},
    {className: "from-blue-400", rules: "--tw-gradient-from: #60a5fa;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(96, 165, 250, 0));"},
    {className: "from-blue-500", rules: "--tw-gradient-from: #3b82f6;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(59, 130, 246, 0));"},
    {className: "from-blue-600", rules: "--tw-gradient-from: #2563eb;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(37, 99, 235, 0));"},
    {className: "from-blue-700", rules: "--tw-gradient-from: #1d4ed8;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(29, 78, 216, 0));"},
    {className: "from-blue-800", rules: "--tw-gradient-from: #1e40af;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(30, 64, 175, 0));"},
    {className: "from-blue-900", rules: "--tw-gradient-from: #1e3a8a;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(30, 58, 138, 0));"},
    {className: "from-indigo-50", rules: "--tw-gradient-from: #eef2ff;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(238, 242, 255, 0));"},
    {className: "from-indigo-100", rules: "--tw-gradient-from: #e0e7ff;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(224, 231, 255, 0));"},
    {className: "from-indigo-200", rules: "--tw-gradient-from: #c7d2fe;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(199, 210, 254, 0));"},
    {className: "from-indigo-300", rules: "--tw-gradient-from: #a5b4fc;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(165, 180, 252, 0));"},
    {className: "from-indigo-400", rules: "--tw-gradient-from: #818cf8;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(129, 140, 248, 0));"},
    {className: "from-indigo-500", rules: "--tw-gradient-from: #6366f1;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(99, 102, 241, 0));"},
    {className: "from-indigo-600", rules: "--tw-gradient-from: #4f46e5;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(79, 70, 229, 0));"},
    {className: "from-indigo-700", rules: "--tw-gradient-from: #4338ca;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(67, 56, 202, 0));"},
    {className: "from-indigo-800", rules: "--tw-gradient-from: #3730a3;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(55, 48, 163, 0));"},
    {className: "from-indigo-900", rules: "--tw-gradient-from: #312e81;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(49, 46, 129, 0));"},
    {className: "from-purple-50", rules: "--tw-gradient-from: #f5f3ff;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(245, 243, 255, 0));"},
    {className: "from-purple-100", rules: "--tw-gradient-from: #ede9fe;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(237, 233, 254, 0));"},
    {className: "from-purple-200", rules: "--tw-gradient-from: #ddd6fe;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(221, 214, 254, 0));"},
    {className: "from-purple-300", rules: "--tw-gradient-from: #c4b5fd;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(196, 181, 253, 0));"},
    {className: "from-purple-400", rules: "--tw-gradient-from: #a78bfa;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(167, 139, 250, 0));"},
    {className: "from-purple-500", rules: "--tw-gradient-from: #8b5cf6;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(139, 92, 246, 0));"},
    {className: "from-purple-600", rules: "--tw-gradient-from: #7c3aed;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(124, 58, 237, 0));"},
    {className: "from-purple-700", rules: "--tw-gradient-from: #6d28d9;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(109, 40, 217, 0));"},
    {className: "from-purple-800", rules: "--tw-gradient-from: #5b21b6;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(91, 33, 182, 0));"},
    {className: "from-purple-900", rules: "--tw-gradient-from: #4c1d95;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(76, 29, 149, 0));"},
    {className: "from-pink-50", rules: "--tw-gradient-from: #fdf2f8;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(253, 242, 248, 0));"},
    {className: "from-pink-100", rules: "--tw-gradient-from: #fce7f3;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(252, 231, 243, 0));"},
    {className: "from-pink-200", rules: "--tw-gradient-from: #fbcfe8;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(251, 207, 232, 0));"},
    {className: "from-pink-300", rules: "--tw-gradient-from: #f9a8d4;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(249, 168, 212, 0));"},
    {className: "from-pink-400", rules: "--tw-gradient-from: #f472b6;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(244, 114, 182, 0));"},
    {className: "from-pink-500", rules: "--tw-gradient-from: #ec4899;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(236, 72, 153, 0));"},
    {className: "from-pink-600", rules: "--tw-gradient-from: #db2777;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(219, 39, 119, 0));"},
    {className: "from-pink-700", rules: "--tw-gradient-from: #be185d;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(190, 24, 93, 0));"},
    {className: "from-pink-800", rules: "--tw-gradient-from: #9d174d;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(157, 23, 77, 0));"},
    {className: "from-pink-900", rules: "--tw-gradient-from: #831843;--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgba(131, 24, 67, 0));"},
    {className: "via-transparent", rules: "--tw-gradient-stops: var(--tw-gradient-from), transparent, var(--tw-gradient-to, rgba(0, 0, 0, 0));"},
    {className: "via-current", rules: "--tw-gradient-stops: var(--tw-gradient-from), currentColor, var(--tw-gradient-to, rgba(255, 255, 255, 0));"},
    {className: "via-black", rules: "--tw-gradient-stops: var(--tw-gradient-from), #000, var(--tw-gradient-to, rgba(0, 0, 0, 0));"},
    {className: "via-white", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fff, var(--tw-gradient-to, rgba(255, 255, 255, 0));"},
    {className: "via-gray-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f9fafb, var(--tw-gradient-to, rgba(249, 250, 251, 0));"},
    {className: "via-gray-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f3f4f6, var(--tw-gradient-to, rgba(243, 244, 246, 0));"},
    {className: "via-gray-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #e5e7eb, var(--tw-gradient-to, rgba(229, 231, 235, 0));"},
    {className: "via-gray-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #d1d5db, var(--tw-gradient-to, rgba(209, 213, 219, 0));"},
    {className: "via-gray-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #9ca3af, var(--tw-gradient-to, rgba(156, 163, 175, 0));"},
    {className: "via-gray-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #6b7280, var(--tw-gradient-to, rgba(107, 114, 128, 0));"},
    {className: "via-gray-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #4b5563, var(--tw-gradient-to, rgba(75, 85, 99, 0));"},
    {className: "via-gray-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #374151, var(--tw-gradient-to, rgba(55, 65, 81, 0));"},
    {className: "via-gray-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #1f2937, var(--tw-gradient-to, rgba(31, 41, 55, 0));"},
    {className: "via-gray-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #111827, var(--tw-gradient-to, rgba(17, 24, 39, 0));"},
    {className: "via-red-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fef2f2, var(--tw-gradient-to, rgba(254, 242, 242, 0));"},
    {className: "via-red-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fee2e2, var(--tw-gradient-to, rgba(254, 226, 226, 0));"},
    {className: "via-red-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fecaca, var(--tw-gradient-to, rgba(254, 202, 202, 0));"},
    {className: "via-red-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fca5a5, var(--tw-gradient-to, rgba(252, 165, 165, 0));"},
    {className: "via-red-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f87171, var(--tw-gradient-to, rgba(248, 113, 113, 0));"},
    {className: "via-red-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #ef4444, var(--tw-gradient-to, rgba(239, 68, 68, 0));"},
    {className: "via-red-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #dc2626, var(--tw-gradient-to, rgba(220, 38, 38, 0));"},
    {className: "via-red-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #b91c1c, var(--tw-gradient-to, rgba(185, 28, 28, 0));"},
    {className: "via-red-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #991b1b, var(--tw-gradient-to, rgba(153, 27, 27, 0));"},
    {className: "via-red-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #7f1d1d, var(--tw-gradient-to, rgba(127, 29, 29, 0));"},
    {className: "via-yellow-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fffbeb, var(--tw-gradient-to, rgba(255, 251, 235, 0));"},
    {className: "via-yellow-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fef3c7, var(--tw-gradient-to, rgba(254, 243, 199, 0));"},
    {className: "via-yellow-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fde68a, var(--tw-gradient-to, rgba(253, 230, 138, 0));"},
    {className: "via-yellow-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fcd34d, var(--tw-gradient-to, rgba(252, 211, 77, 0));"},
    {className: "via-yellow-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fbbf24, var(--tw-gradient-to, rgba(251, 191, 36, 0));"},
    {className: "via-yellow-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f59e0b, var(--tw-gradient-to, rgba(245, 158, 11, 0));"},
    {className: "via-yellow-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #d97706, var(--tw-gradient-to, rgba(217, 119, 6, 0));"},
    {className: "via-yellow-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #b45309, var(--tw-gradient-to, rgba(180, 83, 9, 0));"},
    {className: "via-yellow-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #92400e, var(--tw-gradient-to, rgba(146, 64, 14, 0));"},
    {className: "via-yellow-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #78350f, var(--tw-gradient-to, rgba(120, 53, 15, 0));"},
    {className: "via-green-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #ecfdf5, var(--tw-gradient-to, rgba(236, 253, 245, 0));"},
    {className: "via-green-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #d1fae5, var(--tw-gradient-to, rgba(209, 250, 229, 0));"},
    {className: "via-green-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #a7f3d0, var(--tw-gradient-to, rgba(167, 243, 208, 0));"},
    {className: "via-green-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #6ee7b7, var(--tw-gradient-to, rgba(110, 231, 183, 0));"},
    {className: "via-green-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #34d399, var(--tw-gradient-to, rgba(52, 211, 153, 0));"},
    {className: "via-green-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #10b981, var(--tw-gradient-to, rgba(16, 185, 129, 0));"},
    {className: "via-green-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #059669, var(--tw-gradient-to, rgba(5, 150, 105, 0));"},
    {className: "via-green-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #047857, var(--tw-gradient-to, rgba(4, 120, 87, 0));"},
    {className: "via-green-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #065f46, var(--tw-gradient-to, rgba(6, 95, 70, 0));"},
    {className: "via-green-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #064e3b, var(--tw-gradient-to, rgba(6, 78, 59, 0));"},
    {className: "via-blue-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #eff6ff, var(--tw-gradient-to, rgba(239, 246, 255, 0));"},
    {className: "via-blue-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #dbeafe, var(--tw-gradient-to, rgba(219, 234, 254, 0));"},
    {className: "via-blue-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #bfdbfe, var(--tw-gradient-to, rgba(191, 219, 254, 0));"},
    {className: "via-blue-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #93c5fd, var(--tw-gradient-to, rgba(147, 197, 253, 0));"},
    {className: "via-blue-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #60a5fa, var(--tw-gradient-to, rgba(96, 165, 250, 0));"},
    {className: "via-blue-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #3b82f6, var(--tw-gradient-to, rgba(59, 130, 246, 0));"},
    {className: "via-blue-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #2563eb, var(--tw-gradient-to, rgba(37, 99, 235, 0));"},
    {className: "via-blue-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #1d4ed8, var(--tw-gradient-to, rgba(29, 78, 216, 0));"},
    {className: "via-blue-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #1e40af, var(--tw-gradient-to, rgba(30, 64, 175, 0));"},
    {className: "via-blue-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #1e3a8a, var(--tw-gradient-to, rgba(30, 58, 138, 0));"},
    {className: "via-indigo-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #eef2ff, var(--tw-gradient-to, rgba(238, 242, 255, 0));"},
    {className: "via-indigo-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #e0e7ff, var(--tw-gradient-to, rgba(224, 231, 255, 0));"},
    {className: "via-indigo-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #c7d2fe, var(--tw-gradient-to, rgba(199, 210, 254, 0));"},
    {className: "via-indigo-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #a5b4fc, var(--tw-gradient-to, rgba(165, 180, 252, 0));"},
    {className: "via-indigo-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #818cf8, var(--tw-gradient-to, rgba(129, 140, 248, 0));"},
    {className: "via-indigo-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #6366f1, var(--tw-gradient-to, rgba(99, 102, 241, 0));"},
    {className: "via-indigo-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #4f46e5, var(--tw-gradient-to, rgba(79, 70, 229, 0));"},
    {className: "via-indigo-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #4338ca, var(--tw-gradient-to, rgba(67, 56, 202, 0));"},
    {className: "via-indigo-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #3730a3, var(--tw-gradient-to, rgba(55, 48, 163, 0));"},
    {className: "via-indigo-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #312e81, var(--tw-gradient-to, rgba(49, 46, 129, 0));"},
    {className: "via-purple-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f5f3ff, var(--tw-gradient-to, rgba(245, 243, 255, 0));"},
    {className: "via-purple-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #ede9fe, var(--tw-gradient-to, rgba(237, 233, 254, 0));"},
    {className: "via-purple-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #ddd6fe, var(--tw-gradient-to, rgba(221, 214, 254, 0));"},
    {className: "via-purple-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #c4b5fd, var(--tw-gradient-to, rgba(196, 181, 253, 0));"},
    {className: "via-purple-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #a78bfa, var(--tw-gradient-to, rgba(167, 139, 250, 0));"},
    {className: "via-purple-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #8b5cf6, var(--tw-gradient-to, rgba(139, 92, 246, 0));"},
    {className: "via-purple-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #7c3aed, var(--tw-gradient-to, rgba(124, 58, 237, 0));"},
    {className: "via-purple-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #6d28d9, var(--tw-gradient-to, rgba(109, 40, 217, 0));"},
    {className: "via-purple-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #5b21b6, var(--tw-gradient-to, rgba(91, 33, 182, 0));"},
    {className: "via-purple-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #4c1d95, var(--tw-gradient-to, rgba(76, 29, 149, 0));"},
    {className: "via-pink-50", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fdf2f8, var(--tw-gradient-to, rgba(253, 242, 248, 0));"},
    {className: "via-pink-100", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fce7f3, var(--tw-gradient-to, rgba(252, 231, 243, 0));"},
    {className: "via-pink-200", rules: "--tw-gradient-stops: var(--tw-gradient-from), #fbcfe8, var(--tw-gradient-to, rgba(251, 207, 232, 0));"},
    {className: "via-pink-300", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f9a8d4, var(--tw-gradient-to, rgba(249, 168, 212, 0));"},
    {className: "via-pink-400", rules: "--tw-gradient-stops: var(--tw-gradient-from), #f472b6, var(--tw-gradient-to, rgba(244, 114, 182, 0));"},
    {className: "via-pink-500", rules: "--tw-gradient-stops: var(--tw-gradient-from), #ec4899, var(--tw-gradient-to, rgba(236, 72, 153, 0));"},
    {className: "via-pink-600", rules: "--tw-gradient-stops: var(--tw-gradient-from), #db2777, var(--tw-gradient-to, rgba(219, 39, 119, 0));"},
    {className: "via-pink-700", rules: "--tw-gradient-stops: var(--tw-gradient-from), #be185d, var(--tw-gradient-to, rgba(190, 24, 93, 0));"},
    {className: "via-pink-800", rules: "--tw-gradient-stops: var(--tw-gradient-from), #9d174d, var(--tw-gradient-to, rgba(157, 23, 77, 0));"},
    {className: "via-pink-900", rules: "--tw-gradient-stops: var(--tw-gradient-from), #831843, var(--tw-gradient-to, rgba(131, 24, 67, 0));"},
    {className: "to-transparent", rules: "--tw-gradient-to: transparent;"},
    {className: "to-current", rules: "--tw-gradient-to: currentColor;"},
    {className: "to-black", rules: "--tw-gradient-to: #000;"},
    {className: "to-white", rules: "--tw-gradient-to: #fff;"},
    {className: "to-gray-50", rules: "--tw-gradient-to: #f9fafb;"},
    {className: "to-gray-100", rules: "--tw-gradient-to: #f3f4f6;"},
    {className: "to-gray-200", rules: "--tw-gradient-to: #e5e7eb;"},
    {className: "to-gray-300", rules: "--tw-gradient-to: #d1d5db;"},
    {className: "to-gray-400", rules: "--tw-gradient-to: #9ca3af;"},
    {className: "to-gray-500", rules: "--tw-gradient-to: #6b7280;"},
    {className: "to-gray-600", rules: "--tw-gradient-to: #4b5563;"},
    {className: "to-gray-700", rules: "--tw-gradient-to: #374151;"},
    {className: "to-gray-800", rules: "--tw-gradient-to: #1f2937;"},
    {className: "to-gray-900", rules: "--tw-gradient-to: #111827;"},
    {className: "to-red-50", rules: "--tw-gradient-to: #fef2f2;"},
    {className: "to-red-100", rules: "--tw-gradient-to: #fee2e2;"},
    {className: "to-red-200", rules: "--tw-gradient-to: #fecaca;"},
    {className: "to-red-300", rules: "--tw-gradient-to: #fca5a5;"},
    {className: "to-red-400", rules: "--tw-gradient-to: #f87171;"},
    {className: "to-red-500", rules: "--tw-gradient-to: #ef4444;"},
    {className: "to-red-600", rules: "--tw-gradient-to: #dc2626;"},
    {className: "to-red-700", rules: "--tw-gradient-to: #b91c1c;"},
    {className: "to-red-800", rules: "--tw-gradient-to: #991b1b;"},
    {className: "to-red-900", rules: "--tw-gradient-to: #7f1d1d;"},
    {className: "to-yellow-50", rules: "--tw-gradient-to: #fffbeb;"},
    {className: "to-yellow-100", rules: "--tw-gradient-to: #fef3c7;"},
    {className: "to-yellow-200", rules: "--tw-gradient-to: #fde68a;"},
    {className: "to-yellow-300", rules: "--tw-gradient-to: #fcd34d;"},
    {className: "to-yellow-400", rules: "--tw-gradient-to: #fbbf24;"},
    {className: "to-yellow-500", rules: "--tw-gradient-to: #f59e0b;"},
    {className: "to-yellow-600", rules: "--tw-gradient-to: #d97706;"},
    {className: "to-yellow-700", rules: "--tw-gradient-to: #b45309;"},
    {className: "to-yellow-800", rules: "--tw-gradient-to: #92400e;"},
    {className: "to-yellow-900", rules: "--tw-gradient-to: #78350f;"},
    {className: "to-green-50", rules: "--tw-gradient-to: #ecfdf5;"},
    {className: "to-green-100", rules: "--tw-gradient-to: #d1fae5;"},
    {className: "to-green-200", rules: "--tw-gradient-to: #a7f3d0;"},
    {className: "to-green-300", rules: "--tw-gradient-to: #6ee7b7;"},
    {className: "to-green-400", rules: "--tw-gradient-to: #34d399;"},
    {className: "to-green-500", rules: "--tw-gradient-to: #10b981;"},
    {className: "to-green-600", rules: "--tw-gradient-to: #059669;"},
    {className: "to-green-700", rules: "--tw-gradient-to: #047857;"},
    {className: "to-green-800", rules: "--tw-gradient-to: #065f46;"},
    {className: "to-green-900", rules: "--tw-gradient-to: #064e3b;"},
    {className: "to-blue-50", rules: "--tw-gradient-to: #eff6ff;"},
    {className: "to-blue-100", rules: "--tw-gradient-to: #dbeafe;"},
    {className: "to-blue-200", rules: "--tw-gradient-to: #bfdbfe;"},
    {className: "to-blue-300", rules: "--tw-gradient-to: #93c5fd;"},
    {className: "to-blue-400", rules: "--tw-gradient-to: #60a5fa;"},
    {className: "to-blue-500", rules: "--tw-gradient-to: #3b82f6;"},
    {className: "to-blue-600", rules: "--tw-gradient-to: #2563eb;"},
    {className: "to-blue-700", rules: "--tw-gradient-to: #1d4ed8;"},
    {className: "to-blue-800", rules: "--tw-gradient-to: #1e40af;"},
    {className: "to-blue-900", rules: "--tw-gradient-to: #1e3a8a;"},
    {className: "to-indigo-50", rules: "--tw-gradient-to: #eef2ff;"},
    {className: "to-indigo-100", rules: "--tw-gradient-to: #e0e7ff;"},
    {className: "to-indigo-200", rules: "--tw-gradient-to: #c7d2fe;"},
    {className: "to-indigo-300", rules: "--tw-gradient-to: #a5b4fc;"},
    {className: "to-indigo-400", rules: "--tw-gradient-to: #818cf8;"},
    {className: "to-indigo-500", rules: "--tw-gradient-to: #6366f1;"},
    {className: "to-indigo-600", rules: "--tw-gradient-to: #4f46e5;"},
    {className: "to-indigo-700", rules: "--tw-gradient-to: #4338ca;"},
    {className: "to-indigo-800", rules: "--tw-gradient-to: #3730a3;"},
    {className: "to-indigo-900", rules: "--tw-gradient-to: #312e81;"},
    {className: "to-purple-50", rules: "--tw-gradient-to: #f5f3ff;"},
    {className: "to-purple-100", rules: "--tw-gradient-to: #ede9fe;"},
    {className: "to-purple-200", rules: "--tw-gradient-to: #ddd6fe;"},
    {className: "to-purple-300", rules: "--tw-gradient-to: #c4b5fd;"},
    {className: "to-purple-400", rules: "--tw-gradient-to: #a78bfa;"},
    {className: "to-purple-500", rules: "--tw-gradient-to: #8b5cf6;"},
    {className: "to-purple-600", rules: "--tw-gradient-to: #7c3aed;"},
    {className: "to-purple-700", rules: "--tw-gradient-to: #6d28d9;"},
    {className: "to-purple-800", rules: "--tw-gradient-to: #5b21b6;"},
    {className: "to-purple-900", rules: "--tw-gradient-to: #4c1d95;"},
    {className: "to-pink-50", rules: "--tw-gradient-to: #fdf2f8;"},
    {className: "to-pink-100", rules: "--tw-gradient-to: #fce7f3;"},
    {className: "to-pink-200", rules: "--tw-gradient-to: #fbcfe8;"},
    {className: "to-pink-300", rules: "--tw-gradient-to: #f9a8d4;"},
    {className: "to-pink-400", rules: "--tw-gradient-to: #f472b6;"},
    {className: "to-pink-500", rules: "--tw-gradient-to: #ec4899;"},
    {className: "to-pink-600", rules: "--tw-gradient-to: #db2777;"},
    {className: "to-pink-700", rules: "--tw-gradient-to: #be185d;"},
    {className: "to-pink-800", rules: "--tw-gradient-to: #9d174d;"},
    {className: "to-pink-900", rules: "--tw-gradient-to: #831843;"}
]