export const classes = [
    {className: "rounded-none", rules: "border-radius: 0px;"},
    {className: "rounded-sm", rules: "border-radius: 0.125rem;"},
    {className: "rounded", rules: "border-radius: 0.25rem;"},
    {className: "rounded-md", rules: "border-radius: 0.375rem;"},
    {className: "rounded-lg", rules: "border-radius: 0.5rem;"},
    {className: "rounded-xl", rules: "border-radius: 0.75rem;"},
    {className: "rounded-2xl", rules: "border-radius: 1rem;"},
    {className: "rounded-3xl", rules: "border-radius: 1.5rem;"},
    {className: "rounded-full", rules: "border-radius: 9999px;"},
    {className: "rounded-t-none", rules: "border-top-left-radius: 0px;border-top-right-radius: 0px;"},
    {className: "rounded-r-none", rules: "border-top-right-radius: 0px;border-bottom-right-radius: 0px;"},
    {className: "rounded-b-none", rules: "border-bottom-right-radius: 0px;border-bottom-left-radius: 0px;"},
    {className: "rounded-l-none", rules: "border-top-left-radius: 0px;border-bottom-left-radius: 0px;"},
    {className: "rounded-t-sm", rules: "border-top-left-radius: 0.125rem;border-top-right-radius: 0.125rem;"},
    {className: "rounded-r-sm", rules: "border-top-right-radius: 0.125rem;border-bottom-right-radius: 0.125rem;"},
    {className: "rounded-b-sm", rules: "border-bottom-right-radius: 0.125rem;border-bottom-left-radius: 0.125rem;"},
    {className: "rounded-l-sm", rules: "border-top-left-radius: 0.125rem;border-bottom-left-radius: 0.125rem;"},
    {className: "rounded-t", rules: "border-top-left-radius: 0.25rem;border-top-right-radius: 0.25rem;"},
    {className: "rounded-r", rules: "border-top-right-radius: 0.25rem;border-bottom-right-radius: 0.25rem;"},
    {className: "rounded-b", rules: "border-bottom-right-radius: 0.25rem;border-bottom-left-radius: 0.25rem;"},
    {className: "rounded-l", rules: "border-top-left-radius: 0.25rem;border-bottom-left-radius: 0.25rem;"},
    {className: "rounded-t-md", rules: "border-top-left-radius: 0.375rem;border-top-right-radius: 0.375rem;"},
    {className: "rounded-r-md", rules: "border-top-right-radius: 0.375rem;border-bottom-right-radius: 0.375rem;"},
    {className: "rounded-b-md", rules: "border-bottom-right-radius: 0.375rem;border-bottom-left-radius: 0.375rem;"},
    {className: "rounded-l-md", rules: "border-top-left-radius: 0.375rem;border-bottom-left-radius: 0.375rem;"},
    {className: "rounded-t-lg", rules: "border-top-left-radius: 0.5rem;border-top-right-radius: 0.5rem;"},
    {className: "rounded-r-lg", rules: "border-top-right-radius: 0.5rem;border-bottom-right-radius: 0.5rem;"},
    {className: "rounded-b-lg", rules: "border-bottom-right-radius: 0.5rem;border-bottom-left-radius: 0.5rem;"},
    {className: "rounded-l-lg", rules: "border-top-left-radius: 0.5rem;border-bottom-left-radius: 0.5rem;"},
    {className: "rounded-t-xl", rules: "border-top-left-radius: 0.75rem;border-top-right-radius: 0.75rem;"},
    {className: "rounded-r-xl", rules: "border-top-right-radius: 0.75rem;border-bottom-right-radius: 0.75rem;"},
    {className: "rounded-b-xl", rules: "border-bottom-right-radius: 0.75rem;border-bottom-left-radius: 0.75rem;"},
    {className: "rounded-l-xl", rules: "border-top-left-radius: 0.75rem;border-bottom-left-radius: 0.75rem;"},
    {className: "rounded-t-2xl", rules: "border-top-left-radius: 1rem;border-top-right-radius: 1rem;"},
    {className: "rounded-r-2xl", rules: "border-top-right-radius: 1rem;border-bottom-right-radius: 1rem;"},
    {className: "rounded-b-2xl", rules: "border-bottom-right-radius: 1rem;border-bottom-left-radius: 1rem;"},
    {className: "rounded-l-2xl", rules: "border-top-left-radius: 1rem;border-bottom-left-radius: 1rem;"},
    {className: "rounded-t-3xl", rules: "border-top-left-radius: 1.5rem;border-top-right-radius: 1.5rem;"},
    {className: "rounded-r-3xl", rules: "border-top-right-radius: 1.5rem;border-bottom-right-radius: 1.5rem;"},
    {className: "rounded-b-3xl", rules: "border-bottom-right-radius: 1.5rem;border-bottom-left-radius: 1.5rem;"},
    {className: "rounded-l-3xl", rules: "border-top-left-radius: 1.5rem;border-bottom-left-radius: 1.5rem;"},
    {className: "rounded-t-full", rules: "border-top-left-radius: 9999px;border-top-right-radius: 9999px;"},
    {className: "rounded-r-full", rules: "border-top-right-radius: 9999px;border-bottom-right-radius: 9999px;"},
    {className: "rounded-b-full", rules: "border-bottom-right-radius: 9999px;border-bottom-left-radius: 9999px;"},
    {className: "rounded-l-full", rules: "border-top-left-radius: 9999px;border-bottom-left-radius: 9999px;"},
    {className: "rounded-tl-none", rules: "border-top-left-radius: 0px;"},
    {className: "rounded-tr-none", rules: "border-top-right-radius: 0px;"},
    {className: "rounded-br-none", rules: "border-bottom-right-radius: 0px;"},
    {className: "rounded-bl-none", rules: "border-bottom-left-radius: 0px;"},
    {className: "rounded-tl-sm", rules: "border-top-left-radius: 0.125rem;"},
    {className: "rounded-tr-sm", rules: "border-top-right-radius: 0.125rem;"},
    {className: "rounded-br-sm", rules: "border-bottom-right-radius: 0.125rem;"},
    {className: "rounded-bl-sm", rules: "border-bottom-left-radius: 0.125rem;"},
    {className: "rounded-tl", rules: "border-top-left-radius: 0.25rem;"},
    {className: "rounded-tr", rules: "border-top-right-radius: 0.25rem;"},
    {className: "rounded-br", rules: "border-bottom-right-radius: 0.25rem;"},
    {className: "rounded-bl", rules: "border-bottom-left-radius: 0.25rem;"},
    {className: "rounded-tl-md", rules: "border-top-left-radius: 0.375rem;"},
    {className: "rounded-tr-md", rules: "border-top-right-radius: 0.375rem;"},
    {className: "rounded-br-md", rules: "border-bottom-right-radius: 0.375rem;"},
    {className: "rounded-bl-md", rules: "border-bottom-left-radius: 0.375rem;"},
    {className: "rounded-tl-lg", rules: "border-top-left-radius: 0.5rem;"},
    {className: "rounded-tr-lg", rules: "border-top-right-radius: 0.5rem;"},
    {className: "rounded-br-lg", rules: "border-bottom-right-radius: 0.5rem;"},
    {className: "rounded-bl-lg", rules: "border-bottom-left-radius: 0.5rem;"},
    {className: "rounded-tl-xl", rules: "border-top-left-radius: 0.75rem;"},
    {className: "rounded-tr-xl", rules: "border-top-right-radius: 0.75rem;"},
    {className: "rounded-br-xl", rules: "border-bottom-right-radius: 0.75rem;"},
    {className: "rounded-bl-xl", rules: "border-bottom-left-radius: 0.75rem;"},
    {className: "rounded-tl-2xl", rules: "border-top-left-radius: 1rem;"},
    {className: "rounded-tr-2xl", rules: "border-top-right-radius: 1rem;"},
    {className: "rounded-br-2xl", rules: "border-bottom-right-radius: 1rem;"},
    {className: "rounded-bl-2xl", rules: "border-bottom-left-radius: 1rem;"},
    {className: "rounded-tl-3xl", rules: "border-top-left-radius: 1.5rem;"},
    {className: "rounded-tr-3xl", rules: "border-top-right-radius: 1.5rem;"},
    {className: "rounded-br-3xl", rules: "border-bottom-right-radius: 1.5rem;"},
    {className: "rounded-bl-3xl", rules: "border-bottom-left-radius: 1.5rem;"},
    {className: "rounded-tl-full", rules: "border-top-left-radius: 9999px;"},
    {className: "rounded-tr-full", rules: "border-top-right-radius: 9999px;"},
    {className: "rounded-br-full", rules: "border-bottom-right-radius: 9999px;"},
    {className: "rounded-bl-full", rules: "border-bottom-left-radius: 9999px;"},
    {className: "border-0", rules: "border-width: 0px;"},
    {className: "border-2", rules: "border-width: 2px;"},
    {className: "border-4", rules: "border-width: 4px;"},
    {className: "border-8", rules: "border-width: 8px;"},
    {className: "border", rules: "border-width: 1px;"},
    {className: "border-t-0", rules: "border-top-width: 0px;"},
    {className: "border-r-0", rules: "border-right-width: 0px;"},
    {className: "border-b-0", rules: "border-bottom-width: 0px;"},
    {className: "border-l-0", rules: "border-left-width: 0px;"},
    {className: "border-t-2", rules: "border-top-width: 2px;"},
    {className: "border-r-2", rules: "border-right-width: 2px;"},
    {className: "border-b-2", rules: "border-bottom-width: 2px;"},
    {className: "border-l-2", rules: "border-left-width: 2px;"},
    {className: "border-t-4", rules: "border-top-width: 4px;"},
    {className: "border-r-4", rules: "border-right-width: 4px;"},
    {className: "border-b-4", rules: "border-bottom-width: 4px;"},
    {className: "border-l-4", rules: "border-left-width: 4px;"},
    {className: "border-t-8", rules: "border-top-width: 8px;"},
    {className: "border-r-8", rules: "border-right-width: 8px;"},
    {className: "border-b-8", rules: "border-bottom-width: 8px;"},
    {className: "border-l-8", rules: "border-left-width: 8px;"},
    {className: "border-t", rules: "border-top-width: 1px;"},
    {className: "border-r", rules: "border-right-width: 1px;"},
    {className: "border-b", rules: "border-bottom-width: 1px;"},
    {className: "border-l", rules: "border-left-width: 1px;"},
    {className: "border-transparent", rules: "border-color: transparent;"},
    {className: "border-current", rules: "border-color: currentColor;"},
    {className: "border-black", rules: "--tw-border-opacity: 1;border-color: rgba(0, 0, 0, var(--tw-border-opacity));"},
    {className: "border-white", rules: "--tw-border-opacity: 1;border-color: rgba(255, 255, 255, var(--tw-border-opacity));"},
    {className: "border-gray-50", rules: "--tw-border-opacity: 1;border-color: rgba(249, 250, 251, var(--tw-border-opacity));"},
    {className: "border-gray-100", rules: "--tw-border-opacity: 1;border-color: rgba(243, 244, 246, var(--tw-border-opacity));"},
    {className: "border-gray-200", rules: "--tw-border-opacity: 1;border-color: rgba(229, 231, 235, var(--tw-border-opacity));"},
    {className: "border-gray-300", rules: "--tw-border-opacity: 1;border-color: rgba(209, 213, 219, var(--tw-border-opacity));"},
    {className: "border-gray-400", rules: "--tw-border-opacity: 1;border-color: rgba(156, 163, 175, var(--tw-border-opacity));"},
    {className: "border-gray-500", rules: "--tw-border-opacity: 1;border-color: rgba(107, 114, 128, var(--tw-border-opacity));"},
    {className: "border-gray-600", rules: "--tw-border-opacity: 1;border-color: rgba(75, 85, 99, var(--tw-border-opacity));"},
    {className: "border-gray-700", rules: "--tw-border-opacity: 1;border-color: rgba(55, 65, 81, var(--tw-border-opacity));"},
    {className: "border-gray-800", rules: "--tw-border-opacity: 1;border-color: rgba(31, 41, 55, var(--tw-border-opacity));"},
    {className: "border-gray-900", rules: "--tw-border-opacity: 1;border-color: rgba(17, 24, 39, var(--tw-border-opacity));"},
    {className: "border-red-50", rules: "--tw-border-opacity: 1;border-color: rgba(254, 242, 242, var(--tw-border-opacity));"},
    {className: "border-red-100", rules: "--tw-border-opacity: 1;border-color: rgba(254, 226, 226, var(--tw-border-opacity));"},
    {className: "border-red-200", rules: "--tw-border-opacity: 1;border-color: rgba(254, 202, 202, var(--tw-border-opacity));"},
    {className: "border-red-300", rules: "--tw-border-opacity: 1;border-color: rgba(252, 165, 165, var(--tw-border-opacity));"},
    {className: "border-red-400", rules: "--tw-border-opacity: 1;border-color: rgba(248, 113, 113, var(--tw-border-opacity));"},
    {className: "border-red-500", rules: "--tw-border-opacity: 1;border-color: rgba(239, 68, 68, var(--tw-border-opacity));"},
    {className: "border-red-600", rules: "--tw-border-opacity: 1;border-color: rgba(220, 38, 38, var(--tw-border-opacity));"},
    {className: "border-red-700", rules: "--tw-border-opacity: 1;border-color: rgba(185, 28, 28, var(--tw-border-opacity));"},
    {className: "border-red-800", rules: "--tw-border-opacity: 1;border-color: rgba(153, 27, 27, var(--tw-border-opacity));"},
    {className: "border-red-900", rules: "--tw-border-opacity: 1;border-color: rgba(127, 29, 29, var(--tw-border-opacity));"},
    {className: "border-yellow-50", rules: "--tw-border-opacity: 1;border-color: rgba(255, 251, 235, var(--tw-border-opacity));"},
    {className: "border-yellow-100", rules: "--tw-border-opacity: 1;border-color: rgba(254, 243, 199, var(--tw-border-opacity));"},
    {className: "border-yellow-200", rules: "--tw-border-opacity: 1;border-color: rgba(253, 230, 138, var(--tw-border-opacity));"},
    {className: "border-yellow-300", rules: "--tw-border-opacity: 1;border-color: rgba(252, 211, 77, var(--tw-border-opacity));"},
    {className: "border-yellow-400", rules: "--tw-border-opacity: 1;border-color: rgba(251, 191, 36, var(--tw-border-opacity));"},
    {className: "border-yellow-500", rules: "--tw-border-opacity: 1;border-color: rgba(245, 158, 11, var(--tw-border-opacity));"},
    {className: "border-yellow-600", rules: "--tw-border-opacity: 1;border-color: rgba(217, 119, 6, var(--tw-border-opacity));"},
    {className: "border-yellow-700", rules: "--tw-border-opacity: 1;border-color: rgba(180, 83, 9, var(--tw-border-opacity));"},
    {className: "border-yellow-800", rules: "--tw-border-opacity: 1;border-color: rgba(146, 64, 14, var(--tw-border-opacity));"},
    {className: "border-yellow-900", rules: "--tw-border-opacity: 1;border-color: rgba(120, 53, 15, var(--tw-border-opacity));"},
    {className: "border-green-50", rules: "--tw-border-opacity: 1;border-color: rgba(236, 253, 245, var(--tw-border-opacity));"},
    {className: "border-green-100", rules: "--tw-border-opacity: 1;border-color: rgba(209, 250, 229, var(--tw-border-opacity));"},
    {className: "border-green-200", rules: "--tw-border-opacity: 1;border-color: rgba(167, 243, 208, var(--tw-border-opacity));"},
    {className: "border-green-300", rules: "--tw-border-opacity: 1;border-color: rgba(110, 231, 183, var(--tw-border-opacity));"},
    {className: "border-green-400", rules: "--tw-border-opacity: 1;border-color: rgba(52, 211, 153, var(--tw-border-opacity));"},
    {className: "border-green-500", rules: "--tw-border-opacity: 1;border-color: rgba(16, 185, 129, var(--tw-border-opacity));"},
    {className: "border-green-600", rules: "--tw-border-opacity: 1;border-color: rgba(5, 150, 105, var(--tw-border-opacity));"},
    {className: "border-green-700", rules: "--tw-border-opacity: 1;border-color: rgba(4, 120, 87, var(--tw-border-opacity));"},
    {className: "border-green-800", rules: "--tw-border-opacity: 1;border-color: rgba(6, 95, 70, var(--tw-border-opacity));"},
    {className: "border-green-900", rules: "--tw-border-opacity: 1;border-color: rgba(6, 78, 59, var(--tw-border-opacity));"},
    {className: "border-blue-50", rules: "--tw-border-opacity: 1;border-color: rgba(239, 246, 255, var(--tw-border-opacity));"},
    {className: "border-blue-100", rules: "--tw-border-opacity: 1;border-color: rgba(219, 234, 254, var(--tw-border-opacity));"},
    {className: "border-blue-200", rules: "--tw-border-opacity: 1;border-color: rgba(191, 219, 254, var(--tw-border-opacity));"},
    {className: "border-blue-300", rules: "--tw-border-opacity: 1;border-color: rgba(147, 197, 253, var(--tw-border-opacity));"},
    {className: "border-blue-400", rules: "--tw-border-opacity: 1;border-color: rgba(96, 165, 250, var(--tw-border-opacity));"},
    {className: "border-blue-500", rules: "--tw-border-opacity: 1;border-color: rgba(59, 130, 246, var(--tw-border-opacity));"},
    {className: "border-blue-600", rules: "--tw-border-opacity: 1;border-color: rgba(37, 99, 235, var(--tw-border-opacity));"},
    {className: "border-blue-700", rules: "--tw-border-opacity: 1;border-color: rgba(29, 78, 216, var(--tw-border-opacity));"},
    {className: "border-blue-800", rules: "--tw-border-opacity: 1;border-color: rgba(30, 64, 175, var(--tw-border-opacity));"},
    {className: "border-blue-900", rules: "--tw-border-opacity: 1;border-color: rgba(30, 58, 138, var(--tw-border-opacity));"},
    {className: "border-indigo-50", rules: "--tw-border-opacity: 1;border-color: rgba(238, 242, 255, var(--tw-border-opacity));"},
    {className: "border-indigo-100", rules: "--tw-border-opacity: 1;border-color: rgba(224, 231, 255, var(--tw-border-opacity));"},
    {className: "border-indigo-200", rules: "--tw-border-opacity: 1;border-color: rgba(199, 210, 254, var(--tw-border-opacity));"},
    {className: "border-indigo-300", rules: "--tw-border-opacity: 1;border-color: rgba(165, 180, 252, var(--tw-border-opacity));"},
    {className: "border-indigo-400", rules: "--tw-border-opacity: 1;border-color: rgba(129, 140, 248, var(--tw-border-opacity));"},
    {className: "border-indigo-500", rules: "--tw-border-opacity: 1;border-color: rgba(99, 102, 241, var(--tw-border-opacity));"},
    {className: "border-indigo-600", rules: "--tw-border-opacity: 1;border-color: rgba(79, 70, 229, var(--tw-border-opacity));"},
    {className: "border-indigo-700", rules: "--tw-border-opacity: 1;border-color: rgba(67, 56, 202, var(--tw-border-opacity));"},
    {className: "border-indigo-800", rules: "--tw-border-opacity: 1;border-color: rgba(55, 48, 163, var(--tw-border-opacity));"},
    {className: "border-indigo-900", rules: "--tw-border-opacity: 1;border-color: rgba(49, 46, 129, var(--tw-border-opacity));"},
    {className: "border-purple-50", rules: "--tw-border-opacity: 1;border-color: rgba(245, 243, 255, var(--tw-border-opacity));"},
    {className: "border-purple-100", rules: "--tw-border-opacity: 1;border-color: rgba(237, 233, 254, var(--tw-border-opacity));"},
    {className: "border-purple-200", rules: "--tw-border-opacity: 1;border-color: rgba(221, 214, 254, var(--tw-border-opacity));"},
    {className: "border-purple-300", rules: "--tw-border-opacity: 1;border-color: rgba(196, 181, 253, var(--tw-border-opacity));"},
    {className: "border-purple-400", rules: "--tw-border-opacity: 1;border-color: rgba(167, 139, 250, var(--tw-border-opacity));"},
    {className: "border-purple-500", rules: "--tw-border-opacity: 1;border-color: rgba(139, 92, 246, var(--tw-border-opacity));"},
    {className: "border-purple-600", rules: "--tw-border-opacity: 1;border-color: rgba(124, 58, 237, var(--tw-border-opacity));"},
    {className: "border-purple-700", rules: "--tw-border-opacity: 1;border-color: rgba(109, 40, 217, var(--tw-border-opacity));"},
    {className: "border-purple-800", rules: "--tw-border-opacity: 1;border-color: rgba(91, 33, 182, var(--tw-border-opacity));"},
    {className: "border-purple-900", rules: "--tw-border-opacity: 1;border-color: rgba(76, 29, 149, var(--tw-border-opacity));"},
    {className: "border-pink-50", rules: "--tw-border-opacity: 1;border-color: rgba(253, 242, 248, var(--tw-border-opacity));"},
    {className: "border-pink-100", rules: "--tw-border-opacity: 1;border-color: rgba(252, 231, 243, var(--tw-border-opacity));"},
    {className: "border-pink-200", rules: "--tw-border-opacity: 1;border-color: rgba(251, 207, 232, var(--tw-border-opacity));"},
    {className: "border-pink-300", rules: "--tw-border-opacity: 1;border-color: rgba(249, 168, 212, var(--tw-border-opacity));"},
    {className: "border-pink-400", rules: "--tw-border-opacity: 1;border-color: rgba(244, 114, 182, var(--tw-border-opacity));"},
    {className: "border-pink-500", rules: "--tw-border-opacity: 1;border-color: rgba(236, 72, 153, var(--tw-border-opacity));"},
    {className: "border-pink-600", rules: "--tw-border-opacity: 1;border-color: rgba(219, 39, 119, var(--tw-border-opacity));"},
    {className: "border-pink-700", rules: "--tw-border-opacity: 1;border-color: rgba(190, 24, 93, var(--tw-border-opacity));"},
    {className: "border-pink-800", rules: "--tw-border-opacity: 1;border-color: rgba(157, 23, 77, var(--tw-border-opacity));"},
    {className: "border-pink-900", rules: "--tw-border-opacity: 1;border-color: rgba(131, 24, 67, var(--tw-border-opacity));"},
    {className: "border-opacity-0", rules: "--tw-border-opacity: 0;"},
    {className: "border-opacity-5", rules: "--tw-border-opacity: 0.05;"},
    {className: "border-opacity-10", rules: "--tw-border-opacity: 0.1;"},
    {className: "border-opacity-20", rules: "--tw-border-opacity: 0.2;"},
    {className: "border-opacity-25", rules: "--tw-border-opacity: 0.25;"},
    {className: "border-opacity-30", rules: "--tw-border-opacity: 0.3;"},
    {className: "border-opacity-40", rules: "--tw-border-opacity: 0.4;"},
    {className: "border-opacity-50", rules: "--tw-border-opacity: 0.5;"},
    {className: "border-opacity-60", rules: "--tw-border-opacity: 0.6;"},
    {className: "border-opacity-70", rules: "--tw-border-opacity: 0.7;"},
    {className: "border-opacity-75", rules: "--tw-border-opacity: 0.75;"},
    {className: "border-opacity-80", rules: "--tw-border-opacity: 0.8;"},
    {className: "border-opacity-90", rules: "--tw-border-opacity: 0.9;"},
    {className: "border-opacity-95", rules: "--tw-border-opacity: 0.95;"},
    {className: "border-opacity-100", rules: "--tw-border-opacity: 1;"},
    {className: "border-solid", rules: "border-style: solid;"},
    {className: "border-dashed", rules: "border-style: dashed;"},
    {className: "border-dotted", rules: "border-style: dotted;"},
    {className: "border-double", rules: "border-style: double;"},
    {className: "border-none", rules: "border-style: none;"},
    {className: "divide-y-0", rules: "--tw-divide-y-reverse: 0;border-top-width: calc(0px * calc(1 - var(--tw-divide-y-reverse)));border-bottom-width: calc(0px * var(--tw-divide-y-reverse));"},
    {className: "divide-x-0", rules: "--tw-divide-x-reverse: 0;border-right-width: calc(0px * var(--tw-divide-x-reverse));border-left-width: calc(0px * calc(1 - var(--tw-divide-x-reverse)));"},
    {className: "divide-y-2", rules: "--tw-divide-y-reverse: 0;border-top-width: calc(2px * calc(1 - var(--tw-divide-y-reverse)));border-bottom-width: calc(2px * var(--tw-divide-y-reverse));"},
    {className: "divide-x-2", rules: "--tw-divide-x-reverse: 0;border-right-width: calc(2px * var(--tw-divide-x-reverse));border-left-width: calc(2px * calc(1 - var(--tw-divide-x-reverse)));"},
    {className: "divide-y-4", rules: "--tw-divide-y-reverse: 0;border-top-width: calc(4px * calc(1 - var(--tw-divide-y-reverse)));border-bottom-width: calc(4px * var(--tw-divide-y-reverse));"},
    {className: "divide-x-4", rules: "--tw-divide-x-reverse: 0;border-right-width: calc(4px * var(--tw-divide-x-reverse));border-left-width: calc(4px * calc(1 - var(--tw-divide-x-reverse)));"},
    {className: "divide-y-8", rules: "--tw-divide-y-reverse: 0;border-top-width: calc(8px * calc(1 - var(--tw-divide-y-reverse)));border-bottom-width: calc(8px * var(--tw-divide-y-reverse));"},
    {className: "divide-x-8", rules: "--tw-divide-x-reverse: 0;border-right-width: calc(8px * var(--tw-divide-x-reverse));border-left-width: calc(8px * calc(1 - var(--tw-divide-x-reverse)));"},
    {className: "divide-y", rules: "--tw-divide-y-reverse: 0;border-top-width: calc(1px * calc(1 - var(--tw-divide-y-reverse)));border-bottom-width: calc(1px * var(--tw-divide-y-reverse));"},
    {className: "divide-x", rules: "--tw-divide-x-reverse: 0;border-right-width: calc(1px * var(--tw-divide-x-reverse));border-left-width: calc(1px * calc(1 - var(--tw-divide-x-reverse)));"},
    {className: "divide-y-reverse", rules: "--tw-divide-y-reverse: 1;"},
    {className: "divide-x-reverse", rules: "--tw-divide-x-reverse: 1;"},
    {className: "divide-transparent", rules: "border-color: transparent;"},
    {className: "divide-current", rules: "border-color: currentColor;"},
    {className: "divide-black", rules: "--tw-divide-opacity: 1;border-color: rgba(0, 0, 0, var(--tw-divide-opacity));"},
    {className: "divide-white", rules: "--tw-divide-opacity: 1;border-color: rgba(255, 255, 255, var(--tw-divide-opacity));"},
    {className: "divide-gray-50", rules: "--tw-divide-opacity: 1;border-color: rgba(249, 250, 251, var(--tw-divide-opacity));"},
    {className: "divide-gray-100", rules: "--tw-divide-opacity: 1;border-color: rgba(243, 244, 246, var(--tw-divide-opacity));"},
    {className: "divide-gray-200", rules: "--tw-divide-opacity: 1;border-color: rgba(229, 231, 235, var(--tw-divide-opacity));"},
    {className: "divide-gray-300", rules: "--tw-divide-opacity: 1;border-color: rgba(209, 213, 219, var(--tw-divide-opacity));"},
    {className: "divide-gray-400", rules: "--tw-divide-opacity: 1;border-color: rgba(156, 163, 175, var(--tw-divide-opacity));"},
    {className: "divide-gray-500", rules: "--tw-divide-opacity: 1;border-color: rgba(107, 114, 128, var(--tw-divide-opacity));"},
    {className: "divide-gray-600", rules: "--tw-divide-opacity: 1;border-color: rgba(75, 85, 99, var(--tw-divide-opacity));"},
    {className: "divide-gray-700", rules: "--tw-divide-opacity: 1;border-color: rgba(55, 65, 81, var(--tw-divide-opacity));"},
    {className: "divide-gray-800", rules: "--tw-divide-opacity: 1;border-color: rgba(31, 41, 55, var(--tw-divide-opacity));"},
    {className: "divide-gray-900", rules: "--tw-divide-opacity: 1;border-color: rgba(17, 24, 39, var(--tw-divide-opacity));"},
    {className: "divide-red-50", rules: "--tw-divide-opacity: 1;border-color: rgba(254, 242, 242, var(--tw-divide-opacity));"},
    {className: "divide-red-100", rules: "--tw-divide-opacity: 1;border-color: rgba(254, 226, 226, var(--tw-divide-opacity));"},
    {className: "divide-red-200", rules: "--tw-divide-opacity: 1;border-color: rgba(254, 202, 202, var(--tw-divide-opacity));"},
    {className: "divide-red-300", rules: "--tw-divide-opacity: 1;border-color: rgba(252, 165, 165, var(--tw-divide-opacity));"},
    {className: "divide-red-400", rules: "--tw-divide-opacity: 1;border-color: rgba(248, 113, 113, var(--tw-divide-opacity));"},
    {className: "divide-red-500", rules: "--tw-divide-opacity: 1;border-color: rgba(239, 68, 68, var(--tw-divide-opacity));"},
    {className: "divide-red-600", rules: "--tw-divide-opacity: 1;border-color: rgba(220, 38, 38, var(--tw-divide-opacity));"},
    {className: "divide-red-700", rules: "--tw-divide-opacity: 1;border-color: rgba(185, 28, 28, var(--tw-divide-opacity));"},
    {className: "divide-red-800", rules: "--tw-divide-opacity: 1;border-color: rgba(153, 27, 27, var(--tw-divide-opacity));"},
    {className: "divide-red-900", rules: "--tw-divide-opacity: 1;border-color: rgba(127, 29, 29, var(--tw-divide-opacity));"},
    {className: "divide-yellow-50", rules: "--tw-divide-opacity: 1;border-color: rgba(255, 251, 235, var(--tw-divide-opacity));"},
    {className: "divide-yellow-100", rules: "--tw-divide-opacity: 1;border-color: rgba(254, 243, 199, var(--tw-divide-opacity));"},
    {className: "divide-yellow-200", rules: "--tw-divide-opacity: 1;border-color: rgba(253, 230, 138, var(--tw-divide-opacity));"},
    {className: "divide-yellow-300", rules: "--tw-divide-opacity: 1;border-color: rgba(252, 211, 77, var(--tw-divide-opacity));"},
    {className: "divide-yellow-400", rules: "--tw-divide-opacity: 1;border-color: rgba(251, 191, 36, var(--tw-divide-opacity));"},
    {className: "divide-yellow-500", rules: "--tw-divide-opacity: 1;border-color: rgba(245, 158, 11, var(--tw-divide-opacity));"},
    {className: "divide-yellow-600", rules: "--tw-divide-opacity: 1;border-color: rgba(217, 119, 6, var(--tw-divide-opacity));"},
    {className: "divide-yellow-700", rules: "--tw-divide-opacity: 1;border-color: rgba(180, 83, 9, var(--tw-divide-opacity));"},
    {className: "divide-yellow-800", rules: "--tw-divide-opacity: 1;border-color: rgba(146, 64, 14, var(--tw-divide-opacity));"},
    {className: "divide-yellow-900", rules: "--tw-divide-opacity: 1;border-color: rgba(120, 53, 15, var(--tw-divide-opacity));"},
    {className: "divide-green-50", rules: "--tw-divide-opacity: 1;border-color: rgba(236, 253, 245, var(--tw-divide-opacity));"},
    {className: "divide-green-100", rules: "--tw-divide-opacity: 1;border-color: rgba(209, 250, 229, var(--tw-divide-opacity));"},
    {className: "divide-green-200", rules: "--tw-divide-opacity: 1;border-color: rgba(167, 243, 208, var(--tw-divide-opacity));"},
    {className: "divide-green-300", rules: "--tw-divide-opacity: 1;border-color: rgba(110, 231, 183, var(--tw-divide-opacity));"},
    {className: "divide-green-400", rules: "--tw-divide-opacity: 1;border-color: rgba(52, 211, 153, var(--tw-divide-opacity));"},
    {className: "divide-green-500", rules: "--tw-divide-opacity: 1;border-color: rgba(16, 185, 129, var(--tw-divide-opacity));"},
    {className: "divide-green-600", rules: "--tw-divide-opacity: 1;border-color: rgba(5, 150, 105, var(--tw-divide-opacity));"},
    {className: "divide-green-700", rules: "--tw-divide-opacity: 1;border-color: rgba(4, 120, 87, var(--tw-divide-opacity));"},
    {className: "divide-green-800", rules: "--tw-divide-opacity: 1;border-color: rgba(6, 95, 70, var(--tw-divide-opacity));"},
    {className: "divide-green-900", rules: "--tw-divide-opacity: 1;border-color: rgba(6, 78, 59, var(--tw-divide-opacity));"},
    {className: "divide-blue-50", rules: "--tw-divide-opacity: 1;border-color: rgba(239, 246, 255, var(--tw-divide-opacity));"},
    {className: "divide-blue-100", rules: "--tw-divide-opacity: 1;border-color: rgba(219, 234, 254, var(--tw-divide-opacity));"},
    {className: "divide-blue-200", rules: "--tw-divide-opacity: 1;border-color: rgba(191, 219, 254, var(--tw-divide-opacity));"},
    {className: "divide-blue-300", rules: "--tw-divide-opacity: 1;border-color: rgba(147, 197, 253, var(--tw-divide-opacity));"},
    {className: "divide-blue-400", rules: "--tw-divide-opacity: 1;border-color: rgba(96, 165, 250, var(--tw-divide-opacity));"},
    {className: "divide-blue-500", rules: "--tw-divide-opacity: 1;border-color: rgba(59, 130, 246, var(--tw-divide-opacity));"},
    {className: "divide-blue-600", rules: "--tw-divide-opacity: 1;border-color: rgba(37, 99, 235, var(--tw-divide-opacity));"},
    {className: "divide-blue-700", rules: "--tw-divide-opacity: 1;border-color: rgba(29, 78, 216, var(--tw-divide-opacity));"},
    {className: "divide-blue-800", rules: "--tw-divide-opacity: 1;border-color: rgba(30, 64, 175, var(--tw-divide-opacity));"},
    {className: "divide-blue-900", rules: "--tw-divide-opacity: 1;border-color: rgba(30, 58, 138, var(--tw-divide-opacity));"},
    {className: "divide-indigo-50", rules: "--tw-divide-opacity: 1;border-color: rgba(238, 242, 255, var(--tw-divide-opacity));"},
    {className: "divide-indigo-100", rules: "--tw-divide-opacity: 1;border-color: rgba(224, 231, 255, var(--tw-divide-opacity));"},
    {className: "divide-indigo-200", rules: "--tw-divide-opacity: 1;border-color: rgba(199, 210, 254, var(--tw-divide-opacity));"},
    {className: "divide-indigo-300", rules: "--tw-divide-opacity: 1;border-color: rgba(165, 180, 252, var(--tw-divide-opacity));"},
    {className: "divide-indigo-400", rules: "--tw-divide-opacity: 1;border-color: rgba(129, 140, 248, var(--tw-divide-opacity));"},
    {className: "divide-indigo-500", rules: "--tw-divide-opacity: 1;border-color: rgba(99, 102, 241, var(--tw-divide-opacity));"},
    {className: "divide-indigo-600", rules: "--tw-divide-opacity: 1;border-color: rgba(79, 70, 229, var(--tw-divide-opacity));"},
    {className: "divide-indigo-700", rules: "--tw-divide-opacity: 1;border-color: rgba(67, 56, 202, var(--tw-divide-opacity));"},
    {className: "divide-indigo-800", rules: "--tw-divide-opacity: 1;border-color: rgba(55, 48, 163, var(--tw-divide-opacity));"},
    {className: "divide-indigo-900", rules: "--tw-divide-opacity: 1;border-color: rgba(49, 46, 129, var(--tw-divide-opacity));"},
    {className: "divide-purple-50", rules: "--tw-divide-opacity: 1;border-color: rgba(245, 243, 255, var(--tw-divide-opacity));"},
    {className: "divide-purple-100", rules: "--tw-divide-opacity: 1;border-color: rgba(237, 233, 254, var(--tw-divide-opacity));"},
    {className: "divide-purple-200", rules: "--tw-divide-opacity: 1;border-color: rgba(221, 214, 254, var(--tw-divide-opacity));"},
    {className: "divide-purple-300", rules: "--tw-divide-opacity: 1;border-color: rgba(196, 181, 253, var(--tw-divide-opacity));"},
    {className: "divide-purple-400", rules: "--tw-divide-opacity: 1;border-color: rgba(167, 139, 250, var(--tw-divide-opacity));"},
    {className: "divide-purple-500", rules: "--tw-divide-opacity: 1;border-color: rgba(139, 92, 246, var(--tw-divide-opacity));"},
    {className: "divide-purple-600", rules: "--tw-divide-opacity: 1;border-color: rgba(124, 58, 237, var(--tw-divide-opacity));"},
    {className: "divide-purple-700", rules: "--tw-divide-opacity: 1;border-color: rgba(109, 40, 217, var(--tw-divide-opacity));"},
    {className: "divide-purple-800", rules: "--tw-divide-opacity: 1;border-color: rgba(91, 33, 182, var(--tw-divide-opacity));"},
    {className: "divide-purple-900", rules: "--tw-divide-opacity: 1;border-color: rgba(76, 29, 149, var(--tw-divide-opacity));"},
    {className: "divide-pink-50", rules: "--tw-divide-opacity: 1;border-color: rgba(253, 242, 248, var(--tw-divide-opacity));"},
    {className: "divide-pink-100", rules: "--tw-divide-opacity: 1;border-color: rgba(252, 231, 243, var(--tw-divide-opacity));"},
    {className: "divide-pink-200", rules: "--tw-divide-opacity: 1;border-color: rgba(251, 207, 232, var(--tw-divide-opacity));"},
    {className: "divide-pink-300", rules: "--tw-divide-opacity: 1;border-color: rgba(249, 168, 212, var(--tw-divide-opacity));"},
    {className: "divide-pink-400", rules: "--tw-divide-opacity: 1;border-color: rgba(244, 114, 182, var(--tw-divide-opacity));"},
    {className: "divide-pink-500", rules: "--tw-divide-opacity: 1;border-color: rgba(236, 72, 153, var(--tw-divide-opacity));"},
    {className: "divide-pink-600", rules: "--tw-divide-opacity: 1;border-color: rgba(219, 39, 119, var(--tw-divide-opacity));"},
    {className: "divide-pink-700", rules: "--tw-divide-opacity: 1;border-color: rgba(190, 24, 93, var(--tw-divide-opacity));"},
    {className: "divide-pink-800", rules: "--tw-divide-opacity: 1;border-color: rgba(157, 23, 77, var(--tw-divide-opacity));"},
    {className: "divide-pink-900", rules: "--tw-divide-opacity: 1;border-color: rgba(131, 24, 67, var(--tw-divide-opacity));"},
    {className: "divide-opacity-0", rules: "--tw-divide-opacity: 0;"},
    {className: "divide-opacity-5", rules: "--tw-divide-opacity: 0.05;"},
    {className: "divide-opacity-10", rules: "--tw-divide-opacity: 0.1;"},
    {className: "divide-opacity-20", rules: "--tw-divide-opacity: 0.2;"},
    {className: "divide-opacity-25", rules: "--tw-divide-opacity: 0.25;"},
    {className: "divide-opacity-30", rules: "--tw-divide-opacity: 0.3;"},
    {className: "divide-opacity-40", rules: "--tw-divide-opacity: 0.4;"},
    {className: "divide-opacity-50", rules: "--tw-divide-opacity: 0.5;"},
    {className: "divide-opacity-60", rules: "--tw-divide-opacity: 0.6;"},
    {className: "divide-opacity-70", rules: "--tw-divide-opacity: 0.7;"},
    {className: "divide-opacity-75", rules: "--tw-divide-opacity: 0.75;"},
    {className: "divide-opacity-80", rules: "--tw-divide-opacity: 0.8;"},
    {className: "divide-opacity-90", rules: "--tw-divide-opacity: 0.9;"},
    {className: "divide-opacity-95", rules: "--tw-divide-opacity: 0.95;"},
    {className: "divide-opacity-100", rules: "--tw-divide-opacity: 1;"},
    {className: "divide-solid", rules: "border-style: solid;"},
    {className: "divide-dashed", rules: "border-style: dashed;"},
    {className: "divide-dotted", rules: "border-style: dotted;"},
    {className: "divide-double", rules: "border-style: double;"},
    {className: "divide-none", rules: "border-style: none;"},
    {className: "ring-0", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(0px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring-1", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring-2", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring-4", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(4px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring-8", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(8px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring", rules: "box-shadow: var(--tw-ring-inset) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color);"},
    {className: "ring-inset", rules: "--tw-ring-inset: inset;"},
    {className: "ring-transparent", rules: "--tw-ring-color: transparent;"},
    {className: "ring-current", rules: "--tw-ring-color: currentColor;"},
    {className: "ring-black", rules: "--tw-ring-color: rgba(0, 0, 0, var(--tw-ring-opacity));"},
    {className: "ring-white", rules: "--tw-ring-color: rgba(255, 255, 255, var(--tw-ring-opacity));"},
    {className: "ring-gray-50", rules: "--tw-ring-color: rgba(249, 250, 251, var(--tw-ring-opacity));"},
    {className: "ring-gray-100", rules: "--tw-ring-color: rgba(243, 244, 246, var(--tw-ring-opacity));"},
    {className: "ring-gray-200", rules: "--tw-ring-color: rgba(229, 231, 235, var(--tw-ring-opacity));"},
    {className: "ring-gray-300", rules: "--tw-ring-color: rgba(209, 213, 219, var(--tw-ring-opacity));"},
    {className: "ring-gray-400", rules: "--tw-ring-color: rgba(156, 163, 175, var(--tw-ring-opacity));"},
    {className: "ring-gray-500", rules: "--tw-ring-color: rgba(107, 114, 128, var(--tw-ring-opacity));"},
    {className: "ring-gray-600", rules: "--tw-ring-color: rgba(75, 85, 99, var(--tw-ring-opacity));"},
    {className: "ring-gray-700", rules: "--tw-ring-color: rgba(55, 65, 81, var(--tw-ring-opacity));"},
    {className: "ring-gray-800", rules: "--tw-ring-color: rgba(31, 41, 55, var(--tw-ring-opacity));"},
    {className: "ring-gray-900", rules: "--tw-ring-color: rgba(17, 24, 39, var(--tw-ring-opacity));"},
    {className: "ring-red-50", rules: "--tw-ring-color: rgba(254, 242, 242, var(--tw-ring-opacity));"},
    {className: "ring-red-100", rules: "--tw-ring-color: rgba(254, 226, 226, var(--tw-ring-opacity));"},
    {className: "ring-red-200", rules: "--tw-ring-color: rgba(254, 202, 202, var(--tw-ring-opacity));"},
    {className: "ring-red-300", rules: "--tw-ring-color: rgba(252, 165, 165, var(--tw-ring-opacity));"},
    {className: "ring-red-400", rules: "--tw-ring-color: rgba(248, 113, 113, var(--tw-ring-opacity));"},
    {className: "ring-red-500", rules: "--tw-ring-color: rgba(239, 68, 68, var(--tw-ring-opacity));"},
    {className: "ring-red-600", rules: "--tw-ring-color: rgba(220, 38, 38, var(--tw-ring-opacity));"},
    {className: "ring-red-700", rules: "--tw-ring-color: rgba(185, 28, 28, var(--tw-ring-opacity));"},
    {className: "ring-red-800", rules: "--tw-ring-color: rgba(153, 27, 27, var(--tw-ring-opacity));"},
    {className: "ring-red-900", rules: "--tw-ring-color: rgba(127, 29, 29, var(--tw-ring-opacity));"},
    {className: "ring-yellow-50", rules: "--tw-ring-color: rgba(255, 251, 235, var(--tw-ring-opacity));"},
    {className: "ring-yellow-100", rules: "--tw-ring-color: rgba(254, 243, 199, var(--tw-ring-opacity));"},
    {className: "ring-yellow-200", rules: "--tw-ring-color: rgba(253, 230, 138, var(--tw-ring-opacity));"},
    {className: "ring-yellow-300", rules: "--tw-ring-color: rgba(252, 211, 77, var(--tw-ring-opacity));"},
    {className: "ring-yellow-400", rules: "--tw-ring-color: rgba(251, 191, 36, var(--tw-ring-opacity));"},
    {className: "ring-yellow-500", rules: "--tw-ring-color: rgba(245, 158, 11, var(--tw-ring-opacity));"},
    {className: "ring-yellow-600", rules: "--tw-ring-color: rgba(217, 119, 6, var(--tw-ring-opacity));"},
    {className: "ring-yellow-700", rules: "--tw-ring-color: rgba(180, 83, 9, var(--tw-ring-opacity));"},
    {className: "ring-yellow-800", rules: "--tw-ring-color: rgba(146, 64, 14, var(--tw-ring-opacity));"},
    {className: "ring-yellow-900", rules: "--tw-ring-color: rgba(120, 53, 15, var(--tw-ring-opacity));"},
    {className: "ring-green-50", rules: "--tw-ring-color: rgba(236, 253, 245, var(--tw-ring-opacity));"},
    {className: "ring-green-100", rules: "--tw-ring-color: rgba(209, 250, 229, var(--tw-ring-opacity));"},
    {className: "ring-green-200", rules: "--tw-ring-color: rgba(167, 243, 208, var(--tw-ring-opacity));"},
    {className: "ring-green-300", rules: "--tw-ring-color: rgba(110, 231, 183, var(--tw-ring-opacity));"},
    {className: "ring-green-400", rules: "--tw-ring-color: rgba(52, 211, 153, var(--tw-ring-opacity));"},
    {className: "ring-green-500", rules: "--tw-ring-color: rgba(16, 185, 129, var(--tw-ring-opacity));"},
    {className: "ring-green-600", rules: "--tw-ring-color: rgba(5, 150, 105, var(--tw-ring-opacity));"},
    {className: "ring-green-700", rules: "--tw-ring-color: rgba(4, 120, 87, var(--tw-ring-opacity));"},
    {className: "ring-green-800", rules: "--tw-ring-color: rgba(6, 95, 70, var(--tw-ring-opacity));"},
    {className: "ring-green-900", rules: "--tw-ring-color: rgba(6, 78, 59, var(--tw-ring-opacity));"},
    {className: "ring-blue-50", rules: "--tw-ring-color: rgba(239, 246, 255, var(--tw-ring-opacity));"},
    {className: "ring-blue-100", rules: "--tw-ring-color: rgba(219, 234, 254, var(--tw-ring-opacity));"},
    {className: "ring-blue-200", rules: "--tw-ring-color: rgba(191, 219, 254, var(--tw-ring-opacity));"},
    {className: "ring-blue-300", rules: "--tw-ring-color: rgba(147, 197, 253, var(--tw-ring-opacity));"},
    {className: "ring-blue-400", rules: "--tw-ring-color: rgba(96, 165, 250, var(--tw-ring-opacity));"},
    {className: "ring-blue-500", rules: "--tw-ring-color: rgba(59, 130, 246, var(--tw-ring-opacity));"},
    {className: "ring-blue-600", rules: "--tw-ring-color: rgba(37, 99, 235, var(--tw-ring-opacity));"},
    {className: "ring-blue-700", rules: "--tw-ring-color: rgba(29, 78, 216, var(--tw-ring-opacity));"},
    {className: "ring-blue-800", rules: "--tw-ring-color: rgba(30, 64, 175, var(--tw-ring-opacity));"},
    {className: "ring-blue-900", rules: "--tw-ring-color: rgba(30, 58, 138, var(--tw-ring-opacity));"},
    {className: "ring-indigo-50", rules: "--tw-ring-color: rgba(238, 242, 255, var(--tw-ring-opacity));"},
    {className: "ring-indigo-100", rules: "--tw-ring-color: rgba(224, 231, 255, var(--tw-ring-opacity));"},
    {className: "ring-indigo-200", rules: "--tw-ring-color: rgba(199, 210, 254, var(--tw-ring-opacity));"},
    {className: "ring-indigo-300", rules: "--tw-ring-color: rgba(165, 180, 252, var(--tw-ring-opacity));"},
    {className: "ring-indigo-400", rules: "--tw-ring-color: rgba(129, 140, 248, var(--tw-ring-opacity));"},
    {className: "ring-indigo-500", rules: "--tw-ring-color: rgba(99, 102, 241, var(--tw-ring-opacity));"},
    {className: "ring-indigo-600", rules: "--tw-ring-color: rgba(79, 70, 229, var(--tw-ring-opacity));"},
    {className: "ring-indigo-700", rules: "--tw-ring-color: rgba(67, 56, 202, var(--tw-ring-opacity));"},
    {className: "ring-indigo-800", rules: "--tw-ring-color: rgba(55, 48, 163, var(--tw-ring-opacity));"},
    {className: "ring-indigo-900", rules: "--tw-ring-color: rgba(49, 46, 129, var(--tw-ring-opacity));"},
    {className: "ring-purple-50", rules: "--tw-ring-color: rgba(245, 243, 255, var(--tw-ring-opacity));"},
    {className: "ring-purple-100", rules: "--tw-ring-color: rgba(237, 233, 254, var(--tw-ring-opacity));"},
    {className: "ring-purple-200", rules: "--tw-ring-color: rgba(221, 214, 254, var(--tw-ring-opacity));"},
    {className: "ring-purple-300", rules: "--tw-ring-color: rgba(196, 181, 253, var(--tw-ring-opacity));"},
    {className: "ring-purple-400", rules: "--tw-ring-color: rgba(167, 139, 250, var(--tw-ring-opacity));"},
    {className: "ring-purple-500", rules: "--tw-ring-color: rgba(139, 92, 246, var(--tw-ring-opacity));"},
    {className: "ring-purple-600", rules: "--tw-ring-color: rgba(124, 58, 237, var(--tw-ring-opacity));"},
    {className: "ring-purple-700", rules: "--tw-ring-color: rgba(109, 40, 217, var(--tw-ring-opacity));"},
    {className: "ring-purple-800", rules: "--tw-ring-color: rgba(91, 33, 182, var(--tw-ring-opacity));"},
    {className: "ring-purple-900", rules: "--tw-ring-color: rgba(76, 29, 149, var(--tw-ring-opacity));"},
    {className: "ring-pink-50", rules: "--tw-ring-color: rgba(253, 242, 248, var(--tw-ring-opacity));"},
    {className: "ring-pink-100", rules: "--tw-ring-color: rgba(252, 231, 243, var(--tw-ring-opacity));"},
    {className: "ring-pink-200", rules: "--tw-ring-color: rgba(251, 207, 232, var(--tw-ring-opacity));"},
    {className: "ring-pink-300", rules: "--tw-ring-color: rgba(249, 168, 212, var(--tw-ring-opacity));"},
    {className: "ring-pink-400", rules: "--tw-ring-color: rgba(244, 114, 182, var(--tw-ring-opacity));"},
    {className: "ring-pink-500", rules: "--tw-ring-color: rgba(236, 72, 153, var(--tw-ring-opacity));"},
    {className: "ring-pink-600", rules: "--tw-ring-color: rgba(219, 39, 119, var(--tw-ring-opacity));"},
    {className: "ring-pink-700", rules: "--tw-ring-color: rgba(190, 24, 93, var(--tw-ring-opacity));"},
    {className: "ring-pink-800", rules: "--tw-ring-color: rgba(157, 23, 77, var(--tw-ring-opacity));"},
    {className: "ring-pink-900", rules: "--tw-ring-color: rgba(131, 24, 67, var(--tw-ring-opacity));"},
    {className: "ring-opacity-0", rules: "--tw-ring-opacity: 0;"},
    {className: "ring-opacity-5", rules: "--tw-ring-opacity: 0.05;"},
    {className: "ring-opacity-10", rules: "--tw-ring-opacity: 0.1;"},
    {className: "ring-opacity-20", rules: "--tw-ring-opacity: 0.2;"},
    {className: "ring-opacity-25", rules: "--tw-ring-opacity: 0.25;"},
    {className: "ring-opacity-30", rules: "--tw-ring-opacity: 0.3;"},
    {className: "ring-opacity-40", rules: "--tw-ring-opacity: 0.4;"},
    {className: "ring-opacity-50", rules: "--tw-ring-opacity: 0.5;"},
    {className: "ring-opacity-60", rules: "--tw-ring-opacity: 0.6;"},
    {className: "ring-opacity-70", rules: "--tw-ring-opacity: 0.7;"},
    {className: "ring-opacity-75", rules: "--tw-ring-opacity: 0.75;"},
    {className: "ring-opacity-80", rules: "--tw-ring-opacity: 0.8;"},
    {className: "ring-opacity-90", rules: "--tw-ring-opacity: 0.9;"},
    {className: "ring-opacity-95", rules: "--tw-ring-opacity: 0.95;"},
    {className: "ring-opacity-100", rules: "--tw-ring-opacity: 1;"},
    {className: "ring-offset-0", rules: "--tw-ring-offset-width: 0px;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-1", rules: "--tw-ring-offset-width: 1px;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-2", rules: "--tw-ring-offset-width: 2px;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-4", rules: "--tw-ring-offset-width: 4px;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-8", rules: "--tw-ring-offset-width: 8px;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-transparent", rules: "--tw-ring-offset-color: transparent;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-current", rules: "--tw-ring-offset-color: currentColor;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-black", rules: "--tw-ring-offset-color: #000;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-white", rules: "--tw-ring-offset-color: #fff;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-50", rules: "--tw-ring-offset-color: #f9fafb;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-100", rules: "--tw-ring-offset-color: #f3f4f6;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-200", rules: "--tw-ring-offset-color: #e5e7eb;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-300", rules: "--tw-ring-offset-color: #d1d5db;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-400", rules: "--tw-ring-offset-color: #9ca3af;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-500", rules: "--tw-ring-offset-color: #6b7280;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-600", rules: "--tw-ring-offset-color: #4b5563;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-700", rules: "--tw-ring-offset-color: #374151;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-800", rules: "--tw-ring-offset-color: #1f2937;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-gray-900", rules: "--tw-ring-offset-color: #111827;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-50", rules: "--tw-ring-offset-color: #fef2f2;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-100", rules: "--tw-ring-offset-color: #fee2e2;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-200", rules: "--tw-ring-offset-color: #fecaca;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-300", rules: "--tw-ring-offset-color: #fca5a5;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-400", rules: "--tw-ring-offset-color: #f87171;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-500", rules: "--tw-ring-offset-color: #ef4444;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-600", rules: "--tw-ring-offset-color: #dc2626;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-700", rules: "--tw-ring-offset-color: #b91c1c;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-800", rules: "--tw-ring-offset-color: #991b1b;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-red-900", rules: "--tw-ring-offset-color: #7f1d1d;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-50", rules: "--tw-ring-offset-color: #fffbeb;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-100", rules: "--tw-ring-offset-color: #fef3c7;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-200", rules: "--tw-ring-offset-color: #fde68a;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-300", rules: "--tw-ring-offset-color: #fcd34d;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-400", rules: "--tw-ring-offset-color: #fbbf24;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-500", rules: "--tw-ring-offset-color: #f59e0b;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-600", rules: "--tw-ring-offset-color: #d97706;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-700", rules: "--tw-ring-offset-color: #b45309;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-800", rules: "--tw-ring-offset-color: #92400e;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-yellow-900", rules: "--tw-ring-offset-color: #78350f;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-50", rules: "--tw-ring-offset-color: #ecfdf5;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-100", rules: "--tw-ring-offset-color: #d1fae5;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-200", rules: "--tw-ring-offset-color: #a7f3d0;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-300", rules: "--tw-ring-offset-color: #6ee7b7;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-400", rules: "--tw-ring-offset-color: #34d399;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-500", rules: "--tw-ring-offset-color: #10b981;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-600", rules: "--tw-ring-offset-color: #059669;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-700", rules: "--tw-ring-offset-color: #047857;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-800", rules: "--tw-ring-offset-color: #065f46;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-green-900", rules: "--tw-ring-offset-color: #064e3b;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-50", rules: "--tw-ring-offset-color: #eff6ff;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-100", rules: "--tw-ring-offset-color: #dbeafe;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-200", rules: "--tw-ring-offset-color: #bfdbfe;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-300", rules: "--tw-ring-offset-color: #93c5fd;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-400", rules: "--tw-ring-offset-color: #60a5fa;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-500", rules: "--tw-ring-offset-color: #3b82f6;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-600", rules: "--tw-ring-offset-color: #2563eb;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-700", rules: "--tw-ring-offset-color: #1d4ed8;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-800", rules: "--tw-ring-offset-color: #1e40af;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-blue-900", rules: "--tw-ring-offset-color: #1e3a8a;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-50", rules: "--tw-ring-offset-color: #eef2ff;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-100", rules: "--tw-ring-offset-color: #e0e7ff;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-200", rules: "--tw-ring-offset-color: #c7d2fe;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-300", rules: "--tw-ring-offset-color: #a5b4fc;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-400", rules: "--tw-ring-offset-color: #818cf8;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-500", rules: "--tw-ring-offset-color: #6366f1;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-600", rules: "--tw-ring-offset-color: #4f46e5;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-700", rules: "--tw-ring-offset-color: #4338ca;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-800", rules: "--tw-ring-offset-color: #3730a3;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-indigo-900", rules: "--tw-ring-offset-color: #312e81;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-50", rules: "--tw-ring-offset-color: #f5f3ff;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-100", rules: "--tw-ring-offset-color: #ede9fe;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-200", rules: "--tw-ring-offset-color: #ddd6fe;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-300", rules: "--tw-ring-offset-color: #c4b5fd;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-400", rules: "--tw-ring-offset-color: #a78bfa;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-500", rules: "--tw-ring-offset-color: #8b5cf6;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-600", rules: "--tw-ring-offset-color: #7c3aed;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-700", rules: "--tw-ring-offset-color: #6d28d9;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-800", rules: "--tw-ring-offset-color: #5b21b6;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-purple-900", rules: "--tw-ring-offset-color: #4c1d95;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-50", rules: "--tw-ring-offset-color: #fdf2f8;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-100", rules: "--tw-ring-offset-color: #fce7f3;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-200", rules: "--tw-ring-offset-color: #fbcfe8;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-300", rules: "--tw-ring-offset-color: #f9a8d4;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-400", rules: "--tw-ring-offset-color: #f472b6;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-500", rules: "--tw-ring-offset-color: #ec4899;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-600", rules: "--tw-ring-offset-color: #db2777;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-700", rules: "--tw-ring-offset-color: #be185d;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-800", rules: "--tw-ring-offset-color: #9d174d;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"},
    {className: "ring-offset-pink-900", rules: "--tw-ring-offset-color: #831843;box-shadow: 0 0 0 var(--ring-offset-width) var(--ring-offset-color), var(--ring-shadow);"}
]