export const classes = [
    {className: "grid-cols-1", rules: "grid-template-columns: repeat(1, minmax(0, 1fr));"},
    {className: "grid-cols-2", rules: "grid-template-columns: repeat(2, minmax(0, 1fr));"},
    {className: "grid-cols-3", rules: "grid-template-columns: repeat(3, minmax(0, 1fr));"},
    {className: "grid-cols-4", rules: "grid-template-columns: repeat(4, minmax(0, 1fr));"},
    {className: "grid-cols-5", rules: "grid-template-columns: repeat(5, minmax(0, 1fr));"},
    {className: "grid-cols-6", rules: "grid-template-columns: repeat(6, minmax(0, 1fr));"},
    {className: "grid-cols-7", rules: "grid-template-columns: repeat(7, minmax(0, 1fr));"},
    {className: "grid-cols-8", rules: "grid-template-columns: repeat(8, minmax(0, 1fr));"},
    {className: "grid-cols-9", rules: "grid-template-columns: repeat(9, minmax(0, 1fr));"},
    {className: "grid-cols-10", rules: "grid-template-columns: repeat(10, minmax(0, 1fr));"},
    {className: "grid-cols-11", rules: "grid-template-columns: repeat(11, minmax(0, 1fr));"},
    {className: "grid-cols-12", rules: "grid-template-columns: repeat(12, minmax(0, 1fr));"},
    {className: "grid-cols-none", rules: "grid-template-columns: none;"},
    {className: "col-auto", rules: "grid-column: auto;"},
    {className: "col-span-1", rules: "grid-column: span 1 / span 1;"},
    {className: "col-span-2", rules: "grid-column: span 2 / span 2;"},
    {className: "col-span-3", rules: "grid-column: span 3 / span 3;"},
    {className: "col-span-4", rules: "grid-column: span 4 / span 4;"},
    {className: "col-span-5", rules: "grid-column: span 5 / span 5;"},
    {className: "col-span-6", rules: "grid-column: span 6 / span 6;"},
    {className: "col-span-7", rules: "grid-column: span 7 / span 7;"},
    {className: "col-span-8", rules: "grid-column: span 8 / span 8;"},
    {className: "col-span-9", rules: "grid-column: span 9 / span 9;"},
    {className: "col-span-10", rules: "grid-column: span 10 / span 10;"},
    {className: "col-span-11", rules: "grid-column: span 11 / span 11;"},
    {className: "col-span-12", rules: "grid-column: span 12 / span 12;"},
    {className: "col-span-full", rules: "grid-column: 1 / -1;"},
    {className: "col-start-1", rules: "grid-column-start: 1;"},
    {className: "col-start-2", rules: "grid-column-start: 2;"},
    {className: "col-start-3", rules: "grid-column-start: 3;"},
    {className: "col-start-4", rules: "grid-column-start: 4;"},
    {className: "col-start-5", rules: "grid-column-start: 5;"},
    {className: "col-start-6", rules: "grid-column-start: 6;"},
    {className: "col-start-7", rules: "grid-column-start: 7;"},
    {className: "col-start-8", rules: "grid-column-start: 8;"},
    {className: "col-start-9", rules: "grid-column-start: 9;"},
    {className: "col-start-10", rules: "grid-column-start: 10;"},
    {className: "col-start-11", rules: "grid-column-start: 11;"},
    {className: "col-start-12", rules: "grid-column-start: 12;"},
    {className: "col-start-13", rules: "grid-column-start: 13;"},
    {className: "col-start-auto", rules: "grid-column-start: auto;"},
    {className: "col-end-1", rules: "grid-column-end: 1;"},
    {className: "col-end-2", rules: "grid-column-end: 2;"},
    {className: "col-end-3", rules: "grid-column-end: 3;"},
    {className: "col-end-4", rules: "grid-column-end: 4;"},
    {className: "col-end-5", rules: "grid-column-end: 5;"},
    {className: "col-end-6", rules: "grid-column-end: 6;"},
    {className: "col-end-7", rules: "grid-column-end: 7;"},
    {className: "col-end-8", rules: "grid-column-end: 8;"},
    {className: "col-end-9", rules: "grid-column-end: 9;"},
    {className: "col-end-10", rules: "grid-column-end: 10;"},
    {className: "col-end-11", rules: "grid-column-end: 11;"},
    {className: "col-end-12", rules: "grid-column-end: 12;"},
    {className: "col-end-13", rules: "grid-column-end: 13;"},
    {className: "col-end-auto", rules: "grid-column-end: auto;"},
    {className: "grid-rows-1", rules: "grid-template-rows: repeat(1, minmax(0, 1fr));"},
    {className: "grid-rows-2", rules: "grid-template-rows: repeat(2, minmax(0, 1fr));"},
    {className: "grid-rows-3", rules: "grid-template-rows: repeat(3, minmax(0, 1fr));"},
    {className: "grid-rows-4", rules: "grid-template-rows: repeat(4, minmax(0, 1fr));"},
    {className: "grid-rows-5", rules: "grid-template-rows: repeat(5, minmax(0, 1fr));"},
    {className: "grid-rows-6", rules: "grid-template-rows: repeat(6, minmax(0, 1fr));"},
    {className: "grid-rows-none", rules: "grid-template-rows: none;"},
    {className: "row-auto", rules: "grid-row: auto;"},
    {className: "row-span-1", rules: "grid-row: span 1 / span 1;"},
    {className: "row-span-2", rules: "grid-row: span 2 / span 2;"},
    {className: "row-span-3", rules: "grid-row: span 3 / span 3;"},
    {className: "row-span-4", rules: "grid-row: span 4 / span 4;"},
    {className: "row-span-5", rules: "grid-row: span 5 / span 5;"},
    {className: "row-span-6", rules: "grid-row: span 6 / span 6;"},
    {className: "row-span-full", rules: "grid-row: 1 / -1;"},
    {className: "row-start-1", rules: "grid-row-start: 1;"},
    {className: "row-start-2", rules: "grid-row-start: 2;"},
    {className: "row-start-3", rules: "grid-row-start: 3;"},
    {className: "row-start-4", rules: "grid-row-start: 4;"},
    {className: "row-start-5", rules: "grid-row-start: 5;"},
    {className: "row-start-6", rules: "grid-row-start: 6;"},
    {className: "row-start-7", rules: "grid-row-start: 7;"},
    {className: "row-start-auto", rules: "grid-row-start: auto;"},
    {className: "row-end-1", rules: "grid-row-end: 1;"},
    {className: "row-end-2", rules: "grid-row-end: 2;"},
    {className: "row-end-3", rules: "grid-row-end: 3;"},
    {className: "row-end-4", rules: "grid-row-end: 4;"},
    {className: "row-end-5", rules: "grid-row-end: 5;"},
    {className: "row-end-6", rules: "grid-row-end: 6;"},
    {className: "row-end-7", rules: "grid-row-end: 7;"},
    {className: "row-end-auto", rules: "grid-row-end: auto;"},
    {className: "grid-flow-row", rules: "grid-auto-flow: row;"},
    {className: "grid-flow-col", rules: "grid-auto-flow: column;"},
    {className: "grid-flow-row-dense", rules: "grid-auto-flow: row dense;"},
    {className: "grid-flow-col-dense", rules: "grid-auto-flow: column dense;"},
    {className: "auto-cols-auto", rules: "grid-auto-columns: auto;"},
    {className: "auto-cols-min", rules: "grid-auto-columns: min-content;"},
    {className: "auto-cols-max", rules: "grid-auto-columns: max-content;"},
    {className: "auto-cols-fr", rules: "grid-auto-columns: minmax(0, 1fr);"},
    {className: "auto-rows-auto", rules: "grid-auto-rows: auto;"},
    {className: "auto-rows-min", rules: "grid-auto-rows: min-content;"},
    {className: "auto-rows-max", rules: "grid-auto-rows: max-content;"},
    {className: "auto-rows-fr", rules: "grid-auto-rows: minmax(0, 1fr);"},
    {className: "gap-0", rules: "gap: 0px;"},
    {className: "gap-x-0", rules: "column-gap: 0px;"},
    {className: "gap-y-0", rules: "row-gap: 0px;"},
    {className: "gap-0.5", rules: "gap: 0.125rem;"},
    {className: "gap-x-0.5", rules: "column-gap: 0.125rem;"},
    {className: "gap-y-0.5", rules: "row-gap: 0.125rem;"},
    {className: "gap-1", rules: "gap: 0.25rem;"},
    {className: "gap-x-1", rules: "column-gap: 0.25rem;"},
    {className: "gap-y-1", rules: "row-gap: 0.25rem;"},
    {className: "gap-1.5", rules: "gap: 0.375rem;"},
    {className: "gap-x-1.5", rules: "column-gap: 0.375rem;"},
    {className: "gap-y-1.5", rules: "row-gap: 0.375rem;"},
    {className: "gap-2", rules: "gap: 0.5rem;"},
    {className: "gap-x-2", rules: "column-gap: 0.5rem;"},
    {className: "gap-y-2", rules: "row-gap: 0.5rem;"},
    {className: "gap-2.5", rules: "gap: 0.625rem;"},
    {className: "gap-x-2.5", rules: "column-gap: 0.625rem;"},
    {className: "gap-y-2.5", rules: "row-gap: 0.625rem;"},
    {className: "gap-3", rules: "gap: 0.75rem;"},
    {className: "gap-x-3", rules: "column-gap: 0.75rem;"},
    {className: "gap-y-3", rules: "row-gap: 0.75rem;"},
    {className: "gap-3.5", rules: "gap: 0.875rem;"},
    {className: "gap-x-3.5", rules: "column-gap: 0.875rem;"},
    {className: "gap-y-3.5", rules: "row-gap: 0.875rem;"},
    {className: "gap-4", rules: "gap: 1rem;"},
    {className: "gap-x-4", rules: "column-gap: 1rem;"},
    {className: "gap-y-4", rules: "row-gap: 1rem;"},
    {className: "gap-5", rules: "gap: 1.25rem;"},
    {className: "gap-x-5", rules: "column-gap: 1.25rem;"},
    {className: "gap-y-5", rules: "row-gap: 1.25rem;"},
    {className: "gap-6", rules: "gap: 1.5rem;"},
    {className: "gap-x-6", rules: "column-gap: 1.5rem;"},
    {className: "gap-y-6", rules: "row-gap: 1.5rem;"},
    {className: "gap-7", rules: "gap: 1.75rem;"},
    {className: "gap-x-7", rules: "column-gap: 1.75rem;"},
    {className: "gap-y-7", rules: "row-gap: 1.75rem;"},
    {className: "gap-8", rules: "gap: 2rem;"},
    {className: "gap-x-8", rules: "column-gap: 2rem;"},
    {className: "gap-y-8", rules: "row-gap: 2rem;"},
    {className: "gap-9", rules: "gap: 2.25rem;"},
    {className: "gap-x-9", rules: "column-gap: 2.25rem;"},
    {className: "gap-y-9", rules: "row-gap: 2.25rem;"},
    {className: "gap-10", rules: "gap: 2.5rem;"},
    {className: "gap-x-10", rules: "column-gap: 2.5rem;"},
    {className: "gap-y-10", rules: "row-gap: 2.5rem;"},
    {className: "gap-11", rules: "gap: 2.75rem;"},
    {className: "gap-x-11", rules: "column-gap: 2.75rem;"},
    {className: "gap-y-11", rules: "row-gap: 2.75rem;"},
    {className: "gap-12", rules: "gap: 3rem;"},
    {className: "gap-x-12", rules: "column-gap: 3rem;"},
    {className: "gap-y-12", rules: "row-gap: 3rem;"},
    {className: "gap-14", rules: "gap: 3.5rem;"},
    {className: "gap-x-14", rules: "column-gap: 3.5rem;"},
    {className: "gap-y-14", rules: "row-gap: 3.5rem;"},
    {className: "gap-16", rules: "gap: 4rem;"},
    {className: "gap-x-16", rules: "column-gap: 4rem;"},
    {className: "gap-y-16", rules: "row-gap: 4rem;"},
    {className: "gap-20", rules: "gap: 5rem;"},
    {className: "gap-x-20", rules: "column-gap: 5rem;"},
    {className: "gap-y-20", rules: "row-gap: 5rem;"},
    {className: "gap-24", rules: "gap: 6rem;"},
    {className: "gap-x-24", rules: "column-gap: 6rem;"},
    {className: "gap-y-24", rules: "row-gap: 6rem;"},
    {className: "gap-28", rules: "gap: 7rem;"},
    {className: "gap-x-28", rules: "column-gap: 7rem;"},
    {className: "gap-y-28", rules: "row-gap: 7rem;"},
    {className: "gap-32", rules: "gap: 8rem;"},
    {className: "gap-x-32", rules: "column-gap: 8rem;"},
    {className: "gap-y-32", rules: "row-gap: 8rem;"},
    {className: "gap-36", rules: "gap: 9rem;"},
    {className: "gap-x-36", rules: "column-gap: 9rem;"},
    {className: "gap-y-36", rules: "row-gap: 9rem;"},
    {className: "gap-40", rules: "gap: 10rem;"},
    {className: "gap-x-40", rules: "column-gap: 10rem;"},
    {className: "gap-y-40", rules: "row-gap: 10rem;"},
    {className: "gap-44", rules: "gap: 11rem;"},
    {className: "gap-x-44", rules: "column-gap: 11rem;"},
    {className: "gap-y-44", rules: "row-gap: 11rem;"},
    {className: "gap-48", rules: "gap: 12rem;"},
    {className: "gap-x-48", rules: "column-gap: 12rem;"},
    {className: "gap-y-48", rules: "row-gap: 12rem;"},
    {className: "gap-52", rules: "gap: 13rem;"},
    {className: "gap-x-52", rules: "column-gap: 13rem;"},
    {className: "gap-y-52", rules: "row-gap: 13rem;"},
    {className: "gap-56", rules: "gap: 14rem;"},
    {className: "gap-x-56", rules: "column-gap: 14rem;"},
    {className: "gap-y-56", rules: "row-gap: 14rem;"},
    {className: "gap-60", rules: "gap: 15rem;"},
    {className: "gap-x-60", rules: "column-gap: 15rem;"},
    {className: "gap-y-60", rules: "row-gap: 15rem;"},
    {className: "gap-64", rules: "gap: 16rem;"},
    {className: "gap-x-64", rules: "column-gap: 16rem;"},
    {className: "gap-y-64", rules: "row-gap: 16rem;"},
    {className: "gap-72", rules: "gap: 18rem;"},
    {className: "gap-x-72", rules: "column-gap: 18rem;"},
    {className: "gap-y-72", rules: "row-gap: 18rem;"},
    {className: "gap-80", rules: "gap: 20rem;"},
    {className: "gap-x-80", rules: "column-gap: 20rem;"},
    {className: "gap-y-80", rules: "row-gap: 20rem;"},
    {className: "gap-96", rules: "gap: 24rem;"},
    {className: "gap-x-96", rules: "column-gap: 24rem;"},
    {className: "gap-y-96", rules: "row-gap: 24rem;"},
    {className: "gap-px", rules: "gap: 1px;"},
    {className: "gap-x-px", rules: "column-gap: 1px;"},
    {className: "gap-y-px", rules: "row-gap: 1px;"}
]